import {getAccountUser as getChatGPTUser} from '../../../lib/account-auth';
import {database} from '../../../db/store';
import {matchups} from '../../../lib/matchups';
import {competitors} from '../../../lib/competitors';
import {sampleDebates,samplePeople} from '../../../lib/community';
import {categories} from '../../../lib/categories';
import {z} from 'zod';
export const dynamic='force-dynamic';
async function identity(){const u=await getChatGPTUser();if(!u)return null;const db=database();const now=Date.now();await db.prepare('INSERT INTO users (id,username,favorites,created,active) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET active=excluded.active').bind(u.userId,'NewContender','["mma"]',now,now).run();return u.userId;}
export async function GET(){try{const id=await identity();if(!id)return Response.json({error:'Sign in to save your activity.'},{status:401});const db=database();const tables=['users','predictions','votes','debates','likes','follows','rankings'];const values=await Promise.all(tables.map(t=>db.prepare(t==='users'?'SELECT u.*,CASE WHEN r.number<=200 THEN 1 ELSE 0 END AS earlySupporter FROM users u LEFT JOIN account_rewards r ON r.user=u.id LIMIT 5000':`SELECT * FROM ${t} LIMIT 5000`).all()));const state=Object.fromEntries(tables.map((t,i)=>[t,values[i].results]));const me=values[0].results.find(u=>u.id===id);const results=await db.prepare('SELECT * FROM results WHERE user=?').bind(id).all();return Response.json({...state,me,results:results.results});}catch(e){console.error('Arena read:',e);return Response.json({error:'Could not load saved activity. Please retry.'},{status:503});}}
const operation=z.discriminatedUnion('action',[
z.object({action:z.literal('predict'),matchup:z.string(),winner:z.string(),method:z.enum(['KO/TKO','Submission','Decision']),round:z.number().int().min(1).max(5)}),
z.object({action:z.literal('vote'),matchup:z.string(),competitor:z.string()}),
z.object({action:z.literal('debate'),matchup:z.string(),body:z.string().trim().min(10).max(1200),parent:z.string().nullable().optional()}),
z.object({action:z.literal('like'),debate:z.string()}),z.object({action:z.literal('follow'),target:z.string()}),
z.object({action:z.literal('ranking'),title:z.string().trim().min(3).max(60),category:z.string(),competitors:z.array(z.string()).min(2).max(250)}),z.object({action:z.literal('deleteRanking'),id:z.string()}),
z.object({action:z.literal('profile'),username:z.string().trim().min(3).max(24).regex(/^[a-zA-Z0-9_ ]+$/),favorites:z.array(z.string()).min(1).max(5),bio:z.string().trim().max(180).default(''),location:z.string().trim().max(60).default(''),avatar:z.string().max(90).default('initials'),accent:z.enum(['#c5f74f','#a9afff','#ff9b64','#69dfc2','#ff88ba','#81baff']).default('#c5f74f'),favoriteFighter:z.string().max(90).default('')}),
z.object({action:z.literal('settle'),matchup:z.string(),winner:z.string(),method:z.enum(['KO/TKO','Submission','Decision']),round:z.number().int().min(1).max(5)})]);
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return Response.json({error:'Invalid request origin.'},{status:403});const id=await identity();if(!id)return Response.json({error:'Sign in to participate.'},{status:401});const parsed=operation.safeParse(await req.json());if(!parsed.success)return Response.json({error:parsed.error.issues[0].message},{status:400});const p=parsed.data;const db=database();const now=Date.now();const err=(error:string)=>Response.json({error},{status:400});if('matchup' in p){const m=matchups.find(m=>m.id===p.matchup);if(!m)return err('Unknown matchup.');if('winner' in p&&![m.a,m.b].includes(p.winner))return err('Choose a competitor in this matchup.');if('competitor' in p&&![m.a,m.b].includes(p.competitor))return err('Choose a competitor in this matchup.');if('round' in p&&(p.round>m.rounds||(p.method==='Decision'&&p.round!==m.rounds)))return err('A decision goes the full distance.');}
switch(p.action){
case 'predict':{const result=await db.prepare('SELECT winner FROM results WHERE user=? AND matchup=?').bind(id,p.matchup).first();if(result)return err('This demo matchup is settled. Your pick is locked.');await db.prepare('INSERT INTO predictions (user,matchup,winner,method,round,created) VALUES (?,?,?,?,?,?) ON CONFLICT(user,matchup) DO UPDATE SET winner=excluded.winner,method=excluded.method,round=excluded.round,created=excluded.created').bind(id,p.matchup,p.winner,p.method,p.round,now).run();break;}
case 'vote':await db.prepare('INSERT INTO votes (user,matchup,competitor) VALUES (?,?,?) ON CONFLICT(user,matchup) DO UPDATE SET competitor=excluded.competitor').bind(id,p.matchup,p.competitor).run();break;
case 'debate':{if(p.parent){const parent=sampleDebates.find(d=>d.id===p.parent)??await db.prepare('SELECT * FROM debates WHERE id=?').bind(p.parent).first();if(!parent||parent.matchup!==p.matchup||parent.parent)return err('Reply to a top-level argument in this matchup.');}const latest=await db.prepare('SELECT created FROM debates WHERE user=? ORDER BY created DESC LIMIT 1').bind(id).first<{created:number}>();if(latest&&now-latest.created<5000)return err('Give others a moment to read your argument. Try again in a few seconds.');await db.prepare('INSERT INTO debates (id,user,matchup,body,parent,created) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),id,p.matchup,p.body,p.parent??null,now).run();break;}
case 'like':{const debate=sampleDebates.find(d=>d.id===p.debate)??await db.prepare('SELECT * FROM debates WHERE id=?').bind(p.debate).first();if(!debate)return err('Argument not found.');if(debate.user===id)return err('You cannot upvote your own argument.');const existing=await db.prepare('SELECT user FROM likes WHERE user=? AND debate=?').bind(id,p.debate).first();if(existing)await db.prepare('DELETE FROM likes WHERE user=? AND debate=?').bind(id,p.debate).run();else await db.prepare('INSERT INTO likes (user,debate) VALUES (?,?)').bind(id,p.debate).run();break;}
case 'follow':{if(p.target===id)return err('Choose another contender.');const person=samplePeople.find(u=>u.id===p.target)??await db.prepare('SELECT id FROM users WHERE id=?').bind(p.target).first();if(!person)return err('Contender not found.');const exists=await db.prepare('SELECT user FROM follows WHERE user=? AND target=?').bind(id,p.target).first();if(exists)await db.prepare('DELETE FROM follows WHERE user=? AND target=?').bind(id,p.target).run();else await db.prepare('INSERT INTO follows (user,target) VALUES (?,?)').bind(id,p.target).run();break;}
case 'ranking':if(new Set(p.competitors).size!==p.competitors.length||p.competitors.some(cid=>!competitors.some(c=>c.id===cid&&c.category===p.category)))return err('Choose unique competitors from one category.');await db.prepare('INSERT INTO rankings (id,user,title,category,competitors,created) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),id,p.title,p.category,JSON.stringify(p.competitors),now).run();break;
case 'deleteRanking':await db.prepare('DELETE FROM rankings WHERE id=? AND user=?').bind(p.id,id).run();break;
case 'profile':if(!['initials',...['🥊','🦅','🐐','🔥','👑','🎮'].map(x=>'emoji:'+x),...competitors.map(c=>'fighter:'+c.id)].includes(p.avatar))return err('Choose an available avatar.');if(p.favoriteFighter&&!competitors.some(c=>c.id===p.favoriteFighter))return err('Choose a fighter from the roster.');if(p.favorites.some(c=>!categories.some(x=>x.id===c)))return err('Unknown category.');await db.prepare('UPDATE users SET username=?,favorites=?,bio=?,location=?,avatar=?,accent=?,favoriteFighter=? WHERE id=?').bind(p.username,JSON.stringify([...new Set(p.favorites)]),p.bio,p.location,p.avatar,p.accent,p.favoriteFighter,id).run();break;
case 'settle':{const pick=await db.prepare('SELECT winner FROM predictions WHERE user=? AND matchup=?').bind(id,p.matchup).first();if(!pick)return err('Make your prediction before simulating a result.');const exists=await db.prepare('SELECT winner FROM results WHERE user=? AND matchup=?').bind(id,p.matchup).first();if(exists)return err('This demo result has already been settled.');await db.prepare('INSERT INTO results (user,matchup,winner,method,round,created) VALUES (?,?,?,?,?,?)').bind(id,p.matchup,p.winner,p.method,p.round,now).run();break;}}
return Response.json({ok:true});}catch(e){console.error('Arena save:',e);return Response.json({error:'Could not save that change. Your input has been kept; please try again.'},{status:503});}}
