ALTER TABLE users ADD COLUMN bio TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN location TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN avatar TEXT NOT NULL DEFAULT 'initials';
ALTER TABLE users ADD COLUMN accent TEXT NOT NULL DEFAULT '#c5f74f';
ALTER TABLE users ADD COLUMN favoriteFighter TEXT NOT NULL DEFAULT '';
