import {database} from '../../../db/store';
import {getAccountUser} from '../../../lib/account-auth';
import {ownerIdentity} from '../../../lib/owner';
import {z} from 'zod';
export const dynamic='force-dynamic';
const headers={'Cache-Control':'no-store'};
export async function GET(){try{const account=await getAccountUser(),db=database();const items=await db.prepare(`SELECT s.*,u.username,(SELECT COUNT(*) FROM suggestion_votes v WHERE v.suggestion=s.id) AS votes,EXISTS(SELECT 1 FROM suggestion_votes v WHERE v.suggestion=s.id AND v.user=?) AS voted FROM community_suggestions s JOIN users u ON u.id=s.user WHERE s.status!='Hidden' ORDER BY s.created DESC LIMIT 200`).bind(account?.userId??'').all();return Response.json({items:items.results},{headers});}catch{return Response.json({error:'Suggestions could not load. Please retry.'},{status:503,headers});}}
const input=z.discriminatedUnion('action',[z.object({action:z.literal('create'),title:z.string().trim().min(5).max(100),body:z.string().trim().min(10).max(1200),category:z.enum(['Feature','Fighter','Moment','Shop','Data correction'])}).strict(),z.object({action:z.literal('vote'),id:z.string().uuid(),enabled:z.boolean()}).strict(),z.object({action:z.literal('status'),id:z.string().uuid(),status:z.enum(['Open','Planned','Completed','Hidden'])}).strict()]);
export async function POST(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid request origin.'},{status:403});try{const account=await getAccountUser();if(!account)return Response.json({error:'Sign in to suggest or vote.'},{status:401});const text=await req.text();if(text.length>6000)return Response.json({error:'Request too large.'},{status:413});const parsed=input.safeParse(JSON.parse(text));if(!parsed.success)return Response.json({error:'Check the title, description, and category.'},{status:400});const p=parsed.data,db=database(),user=account.userId;
if(p.action==='create'){const r=await db.prepare('INSERT INTO community_suggestions(id,user,title,body,category,created) SELECT ?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM community_suggestions WHERE user=? AND created>?)<5').bind(crypto.randomUUID(),user,p.title,p.body,p.category,Date.now(),user,Date.now()-86400000).run();if(!r.meta.changes)return Response.json({error:'You can post up to five suggestions per day.'},{status:429});}
else {const item=await db.prepare('SELECT user,status FROM community_suggestions WHERE id=?').bind(p.id).first<{user:string;status:string}>();if(!item||item.status==='Hidden')return Response.json({error:'Suggestion unavailable.'},{status:404});if(p.action==='vote'){if(p.enabled)await db.prepare("INSERT OR IGNORE INTO suggestion_votes SELECT ?,? WHERE EXISTS(SELECT 1 FROM community_suggestions WHERE id=? AND status!='Hidden')").bind(p.id,user,p.id).run();else await db.prepare('DELETE FROM suggestion_votes WHERE suggestion=? AND user=?').bind(p.id,user).run();}else {const owner=await ownerIdentity();if(!owner&&!(p.status==='Hidden'&&item.user===user))return Response.json({error:'Owner permission required.'},{status:403});await db.prepare('UPDATE community_suggestions SET status=? WHERE id=?').bind(p.status,p.id).run();}}
return Response.json({ok:true},{headers});}catch{return Response.json({error:'Could not save. Refresh and try again.'},{status:400,headers});}}
