'use client';
import RecoveryCode from './recovery-code';
import {useState} from 'react';
export default function AccountForm({returnTo,initialRegister=false}:{returnTo:string;initialRegister?:boolean}){
  const[code,setCode]=useState('');const[register,setRegister]=useState(initialRegister);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[visible,setVisible]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);try{const response=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:register?'register':'login',username:data.get('username'),password:data.get('password')})});const result=await response.json() as {error?:string;recoveryCode?:string};if(!response.ok)throw Error(result.error??'Please try again.');if(result.recoveryCode)setCode(result.recoveryCode);else window.location.assign(returnTo);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
  if(code)return <div className="account-scene account-recovery"><div className="account-panel"><RecoveryCode code={code} onDone={()=>window.location.assign(returnTo)}/></div></div>;
  return <div className="account-scene"><div className="account-story"><a href="/" className="logo">VERSUS<span>/</span></a><span className="eyebrow">YOUR NEXT GREAT PICK STARTS HERE</span><h2>Claim your name.<br/><em>Build your legacy.</em></h2><p>Draft your fight team, back your fighters, and turn your Arena Coins into a profile that stands out.</p><div className="account-perks"><span>01 · Your name is yours alone</span><span>02 · Picks and rewards saved across devices</span><span>03 · Free play. Always.</span></div><div className="account-stamp">V/ <small>EVERY MATCHUP HAS A STORY</small></div></div><div className="account-panel"><div className="auth-mode-tabs"><button disabled={busy} type="button" className={!register?'selected':''} onClick={()=>{setRegister(false);setError('');}}>Sign in</button><button disabled={busy} type="button" className={register?'selected':''} onClick={()=>{setRegister(true);setError('');}}>Sign up</button></div><span className="eyebrow">YOUR PLACE IN THE ARENA</span><h1>{register?'Meet your arena.':'Back in your corner.'}</h1><p>{register?'One username. Your picks, your style, your community.':'Your fighters, coins, and collection are waiting.'}</p><form onSubmit={submit}><label>Username<input name="username" required minLength={3} maxLength={24} pattern="[a-zA-Z0-9_ ]+" autoComplete="username" placeholder="Your arena name" autoCapitalize="none" spellCheck={false}/></label><label>Password<input name="password" type={visible?'text':'password'} required minLength={register?12:1} maxLength={128} autoComplete={register?'new-password':'current-password'} placeholder={register?'At least 12 characters':'Your password'}/><button type="button" className="password-toggle" onClick={()=>setVisible(!visible)}>{visible?'Hide password':'Show password'}</button></label><small>{register?'No email needed. After signup, save your private recovery code.':'Already have an account? Use your current username and the same password.'}</small>{error&&<p role="alert" className="account-error">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Please wait…':register?'Create my account →':'Enter the arena →'}</button></form>{!register&&<a href={'/recover?return_to='+encodeURIComponent(returnTo)}>Forgot password?</a>}<p className="account-session-note">Sign-in is remembered for 30 days on this device.</p><a href="/">← Back to the arena</a></div></div>;
}
