'use client';
import {useState,useEffect,useCallback} from 'react';
import {Swords,Flame,Trophy,Target,MessagesSquare,BarChart3,Menu,X,Search,Check,UserRound,ShieldCheck} from 'lucide-react';
import type {AppState} from '../lib/domain';
import {Context} from './arena-context';
import {categories} from '../lib/categories';
import {Home,Rankings,Predictions,Community,Trending,Analytics,Compare} from './pages';
import MatchupPage from './matchup';
import SignOut from './sign-out';
import Profile from './profile-page';
import FantasyPage from './fantasy-page';
import {CoinChip} from './arena-coins';
import UserAvatar from './user-avatar';
import {Announcement} from './owner-panel';
const nav=[['','Arena',Swords],['trending','Trending',Flame],['rankings','Rankings',Trophy],['predictions','Predictions',Target],['fantasy','Fantasy',Trophy],['community','Community',MessagesSquare]] as const;
export default function Arena({path,signedIn,signIn,accountMode=false}:{path:string[];signedIn:boolean;signIn:string;accountMode?:boolean}){const[state,setState]=useState<AppState|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[toast,setToast]=useState('');const[menu,setMenu]=useState(false);const[category,setCategory]=useState('mma');const route=path[0]??'';
const reload=useCallback(async()=>{if(!signedIn){setLoading(false);return;}try{const r=await fetch('/api/arena',{cache:'no-store'});const d=await r.json() as AppState & {error?:string};if(!r.ok)throw Error(d.error);setState(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load saved activity.');}finally{setLoading(false);}},[signedIn]);useEffect(()=>{reload();},[reload]);useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(timer);}},[toast]);
async function act(payload:Record<string,unknown>,message='Saved'){if(!signedIn){setToast('Sign in to save your activity.');return false;}setBusy(true);try{const r=await fetch('/api/arena',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await reload();setToast(message);return true;}catch(e){setToast(e instanceof Error?e.message:'Could not save. Please retry.');return false;}finally{setBusy(false);}}
let page:React.ReactNode;if(category!=='mma'){const c=categories.find(c=>c.id===category)!;page=<div className="future-category"><span className="eyebrow">THE NEXT ARENA</span><h1>{c.name}</h1><p>This arena is coming next. Its comparison system is ready for {c.attributes.join(', ').toLowerCase()}—competitor data is the next step.</p><button className="button primary" onClick={()=>setCategory('mma')}>Explore MMA</button></div>;}else if(route==='matchup')page=<MatchupPage id={path[1]??''}/>;else if(route==='rankings')page=<Rankings/>;else if(route==='predictions')page=<Predictions/>;else if(route==='fantasy')page=<FantasyPage/>;else if(route==='community')page=<Community/>;else if(route==='profile')page=<Profile id={path[1]}/>;else if(route==='trending')page=<Trending/>;else if(route==='analytics')page=<Analytics/>;else if(route==='compare')page=<Compare/>;else if(!route)page=<Home/>;else page=<div className="empty"><h1>Outside the arena.</h1><p>This page doesn’t exist.</p><a className="button primary" href="/">Back to VERSUS</a></div>;
return <Context.Provider value={{state,busy,loading,error,act,reload}}><div className="app"><header className="header"><a href="/" className="logo">VERSUS<span className="logo-mark">/</span></a><nav className={menu?'nav open':'nav'} aria-label="Main navigation">{nav.map(([href,name,Icon])=><a key={href} href={`/${href}`} className={route===href?'active':''}><Icon size={17}/>{name}</a>)}</nav><div className="header-actions"><a className="icon-button compare-link" href="/compare" aria-label="Find a matchup"><Search size={19}/></a>{signedIn?<a href="/profile" className="profile-chip"><UserAvatar person={state?.me}/><span>{state?.me.username??'Your profile'}</span></a>:<div className="auth-links"><a href={signIn} target="_top" className="button ghost">Sign in</a>{accountMode&&<a href={signIn+'&mode=signup'} className="button primary">Join VERSUS</a>}</div>}{signedIn&&accountMode&&<><CoinChip/><SignOut/></>}<button className="menu-toggle icon-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header><div className="category-bar"><div className="category-inner">{categories.map(c=><button className={category===c.id?'selected':''} key={c.id} onClick={()=>setCategory(c.id)}>{c.short}{!c.enabled&&<span>SOON</span>}</button>)}<span className="category-caption">EVERY MATCHUP HAS A STORY.</span></div></div><main>{error&&<div className="error-banner" role="alert">{error}<button onClick={reload}>Retry</button></div>}{!signedIn&&<div className="notice">Explore the matchups. <a href={signIn} target="_top">{accountMode?'Sign in':'Sign in with ChatGPT'}</a> to save picks, rankings, and arguments.</div>}<Announcement/>{page}</main><footer><a className="logo" href="/">VERSUS<span>/</span></a><p>Compare. Debate. Predict.</p><span>Independent fan project · Free predictions · No real-money wagering</span><a href="/analytics"><BarChart3 size={14}/> Analytics</a><a href="/fighter-photo-sources.json" className="source-note" target="_blank"><span>Fighter photos: UFC</span></a><span className="source-note"><ShieldCheck size={14}/> Sourced career data · Opponent-aware career ratings</span></footer>{toast&&<div className="toast" role="status"><Check size={18}/>{toast}</div>}{busy&&<div className="save-status" role="status">Saving…</div>}</div></Context.Provider>;}

