'use client';
import {useState,useEffect,useCallback} from 'react';
import {Trophy,BarChart3,Check,ShieldCheck} from 'lucide-react';
import type {AppState} from '../lib/domain';
import {Context} from './arena-context';
import {categories} from '../lib/categories';
import {Rankings,Community,Trending,Analytics} from './pages';
import MatchupPage from './matchup';
import SiteHeader from './site-header';
import Profile from './profile-page';
import FantasyPage from './fantasy-page';
import PeoplePage from './people-page';
import {SocialContext,type SocialState} from './social-context';
import SettingsPage from './settings-page';
import ShopPage from './shop-page';
import OwnerPage from './owner-page';
import {ArchiveHome,FighterDatabase,FighterProfile,StatCompare} from './fighter-database';
import SuggestionsPage from './suggestions-page';
import MomentsPage from './moments-page';
import CoinLeaderboardPage from './coin-leaderboard-page';
import {Announcement} from './owner-panel';
import RewardsPage from './rewards-page';
import LivePage from './live-page';
import {QuickNavigation,DiscoverPage} from './quick-navigation';
export default function Arena({path,signedIn,signIn,accountMode=false}:{path:string[];signedIn:boolean;signIn:string;accountMode?:boolean}){const[state,setState]=useState<AppState|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[toast,setToast]=useState('');const[category,setCategory]=useState('mma');const[quickOpen,setQuickOpen]=useState(false);useEffect(()=>{const keys=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setQuickOpen(v=>!v);}};window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys);},[]);const route=path[0]??'';const[social,setSocial]=useState<SocialState|null>(null);const[socialBusy,setSocialBusy]=useState(false);const[socialError,setSocialError]=useState('');const[socialToast,setSocialToast]=useState('');
const loadSocial=useCallback(async()=>{if(!signedIn)return;try{const r=await fetch('/api/social',{cache:'no-store'});const d=await r.json() as SocialState&{error?:string};if(!r.ok)throw Error(d.error);setSocial(d);setSocialError('');}catch(e){setSocialError(e instanceof Error?e.message:'Could not load friends.');}},[signedIn]);
useEffect(()=>{void loadSocial();const focus=()=>{if(document.visibilityState==='visible')void loadSocial();};window.addEventListener('focus',focus);const timer=setInterval(focus,30000);return()=>{window.removeEventListener('focus',focus);clearInterval(timer);};},[loadSocial]);
useEffect(()=>{if(socialToast){const timer=setTimeout(()=>setSocialToast(''),4000);return()=>clearTimeout(timer);}},[socialToast]);
const reload=useCallback(async()=>{if(!signedIn){setLoading(false);return;}try{const r=await fetch('/api/arena',{cache:'no-store'});const d=await r.json() as AppState & {error?:string};if(!r.ok)throw Error(d.error);setState(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load saved activity.');}finally{setLoading(false);}},[signedIn]);useEffect(()=>{reload();},[reload]);useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(timer);}},[toast]);
async function act(payload:Record<string,unknown>,message='Saved'){if(!signedIn){setToast('Sign in to save your activity.');return false;}setBusy(true);try{const r=await fetch('/api/arena',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await reload();window.dispatchEvent(new Event('versus-coins-updated'));setToast(message);return true;}catch(e){setToast(e instanceof Error?e.message:'Could not save. Please retry.');return false;}finally{setBusy(false);}}
async function socialAct(action:string,target:string){setSocialBusy(true);setSocialError('');try{const r=await fetch('/api/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,target})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await Promise.all([loadSocial(),reload()]);setSocialToast(({request:'Friend request sent.',accept:'You are now friends.',decline:'Request declined.',cancel:'Request cancelled.',remove:'Friend removed.',block:'Account blocked.',unblock:'Account unblocked.'} as Record<string,string>)[action]??'Saved.');return true;}catch(e){setSocialError(e instanceof Error?e.message:'Could not update friends.');return false;}finally{setSocialBusy(false);}}
const incomingRequests=social?.relationships.filter(r=>r.state==='pending'&&r.requester!==state?.me.id).length??0;
let page:React.ReactNode;if(category!=='mma'){const c=categories.find(c=>c.id===category)!;page=<div className="future-category"><span className="eyebrow">THE NEXT ARENA</span><h1>{c.name}</h1><p>This arena is coming next. Its comparison system is ready for {c.attributes.join(', ').toLowerCase()}—competitor data is the next step.</p><button className="button primary" onClick={()=>setCategory('mma')}>Explore MMA</button></div>;}else if(route==='matchup')page=<MatchupPage id={path[1]??''}/>;else if(route==='rankings')page=<Rankings/>;else if(route==='fantasy')page=<FantasyPage/>;else if(route==='rewards')page=<RewardsPage/>;else if(route==='live'||route==='news')page=<LivePage/>;else if(route==='discover')page=<DiscoverPage/>;else if(route==='people')page=<PeoplePage/>;else if(route==='settings')page=<SettingsPage/>;else if(route==='owner')page=<OwnerPage/>;else if(route==='shop')page=<ShopPage/>;else if(route==='moments')page=<MomentsPage/>;else if(route==='leaderboard')page=<CoinLeaderboardPage/>;else if(route==='community')page=<Community/>;else if(route==='profile')page=<Profile id={path[1]}/>;else if(route==='trending')page=<Trending/>;else if(route==='analytics')page=<Analytics/>;else if(route==='fighters')page=<FighterDatabase/>;else if(route==='fighter')page=<FighterProfile id={path[1]??''}/>;else if(route==='suggestions')page=<SuggestionsPage/>;else if(route==='compare'||route==='predictions')page=<StatCompare/>;else if(!route)page=<ArchiveHome/>;else page=<div className="empty"><h1>Outside the arena.</h1><p>This page doesn’t exist.</p><a className="button primary" href="/">Back to VERSUS</a></div>;
return <Context.Provider value={{state,busy,loading,error,act,reload}}><SocialContext.Provider value={{data:social,busy:socialBusy,error:socialError,refresh:loadSocial,act:socialAct}}><div className={`app ${state?.me.compact?'compact':''} ${state?.me.reduceMotion?'reduce-motion':''}`}><a className="skip-link" href="#main-content">Skip to content</a><SiteHeader route={route} signedIn={signedIn} signIn={signIn} accountMode={accountMode} me={state?.me} requests={incomingRequests} onSearch={()=>setQuickOpen(true)}/><main id="main-content" tabIndex={-1}>{error&&<div className="error-banner" role="alert">{error}<button onClick={reload}>Retry</button></div>}{!signedIn&&<div className="notice">Explore the fighter archive. <a href={signIn} target="_top">{accountMode?'Sign in':'Sign in with ChatGPT'}</a> to build your collection, join fantasy, and meet other fans.</div>}<Announcement/>{socialError&&route!=='people'&&<div className="social-error-banner" role="alert">{socialError}<a href="/people"> Open friends →</a></div>}{page}</main><nav className="mobile-bottom-nav" aria-label="Mobile shortcuts"><a href="/" aria-current={!route?'page':undefined}>Explore</a><a href="/fighters" aria-current={route==='fighters'?'page':undefined}>Fighters</a><a href="/fantasy" aria-current={route==='fantasy'?'page':undefined}>Fight Night</a><a href="/rewards" aria-current={route==='rewards'?'page':undefined}>Earn coins</a></nav><footer><section className="footer-contact" aria-labelledby="contact-heading"><h2 id="contact-heading">Contact me</h2><p>Questions, feedback, or ideas for VERSUS? Get in touch.</p><a href="mailto:liam60177@gmail.com">liam60177@gmail.com ↗</a></section><a href="/discover">Find everything</a><a href="/live">News & live stats</a><a href="/rewards">Earn coins</a><a className="logo" href="/">VERSUS<span>/</span></a><p>Explore. Compare. Collect.</p><span>Independent fan project · UFC archive & fantasy · No real-money wagering</span><a href="/leaderboard"><Trophy size={14}/> Coin leaderboard</a><a href="/moments">UFC Moments</a><a href="/analytics"><BarChart3 size={14}/> Analytics</a><a href="/fighter-photo-sources.json" className="source-note" target="_blank"><span>Fighter photos: UFC</span></a><span className="source-note"><ShieldCheck size={14}/> Sourced career data · Opponent-aware career ratings</span></footer><button className="back-top button outline" onClick={()=>window.scrollTo({top:0,behavior:state?.me.reduceMotion?'instant':'smooth'})}>Back to top ↑</button>{quickOpen&&<QuickNavigation close={()=>setQuickOpen(false)}/>} {toast&&<div className="toast" role="status"><Check size={18}/>{toast}</div>}{busy&&<div className="save-status" role="status">Saving…</div>}{socialToast&&<div className="social-toast" role="status">{socialToast}</div>}</div></SocialContext.Provider></Context.Provider>;}

