'use client';
import {useCallback,useEffect,useState} from 'react';
import {Coins,Sparkles,Trophy} from 'lucide-react';
import type {CoinPick} from '../lib/arena-coins';
import type {FantasyBout,FantasyEvent} from '../lib/fantasy';
export type CoinData={wallet:null|{balance:number;accountNumber:number;earlySupporter:number};picks:CoinPick[];history:{delta:number;reason:string;created:number}[];earlyRemaining:number};
export function useCoins(){const[data,setData]=useState<CoinData|null>(null),[error,setError]=useState('');const reload=useCallback(async()=>{try{const r=await fetch('/api/coins',{cache:'no-store'});const d=await r.json() as CoinData&{error?:string};if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load coins.');}},[]);useEffect(()=>{reload();const t=setInterval(reload,60_000);const update=()=>{reload();};window.addEventListener('versus-coins-updated',update);return()=>{clearInterval(t);window.removeEventListener('versus-coins-updated',update);};},[reload]);return{data,error,reload};}
export function CoinChip(){const{data}=useCoins();return data?.wallet?<a href="/fantasy#arena-coins-wallet" className="coin-chip" aria-label={`${data.wallet.balance} Arena Coins`}><Coins size={16}/><strong>{data.wallet.balance.toLocaleString()}</strong></a>:null;}
export function CoinWallet({data,error,onReload}:{data:CoinData|null;error:string;onReload:()=>void}){return <section id="arena-coins-wallet" className="panel coin-wallet"><div className="coin-wallet-main"><div><span className="eyebrow">ARENA COINS · FREE PLAY</span><h2>Put your picks behind your fighters.</h2><p>Back a fighter before their card locks. A correct pick returns 2× your coins, including the amount you used. Draws, no contests, and cancelled bouts refund your coins.</p></div><div className="coin-balance"><Coins size={26}/><strong>{data?.wallet?data.wallet.balance.toLocaleString():'—'}</strong><span>Your Arena Coins</span></div></div>{error&&<p role="alert">{error} <button className="text-link" onClick={onReload}>Retry</button></p>}{data?.wallet?.earlySupporter?<div className="coin-supporter-gift"><span className="early-supporter-badge"><Trophy size={13}/> Early Supporter</span><p>You’re account #{data.wallet.accountNumber}. Your 1,000-coin welcome gift has been credited.</p></div>:!data?.wallet?<div className="coin-supporter-gift"><Sparkles size={17}/><p>{data&&data.earlyRemaining>0?`${data.earlyRemaining} Early Supporter spots remain. The first 200 accounts get a permanent badge and 1,000 coins.`:'Create an account to get 100 welcome coins and start backing fighters.'}</p><a href="/auth?mode=signup&return_to=%2Ffantasy" className="text-link">Join VERSUS →</a></div>:<p className="form-hint">100 welcome coins for regular accounts. Fantasy lineup drafts stay free, even when your coin balance reaches zero.</p>}<p className="coin-no-cash">Play currency only. No cash value, purchases, transfers, or withdrawals. Draft credits and Arena Coins are separate.</p></section>;}
export function CoinBacking({event,bout,data,onReload}:{event:FantasyEvent;bout:FantasyBout;data:CoinData|null;onReload:()=>void}){
  const[fighter,setFighter]=useState(bout.red.id),[amount,setAmount]=useState('50'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const pick=data?.picks.find(p=>p.event===event.id&&p.bout===bout.id);if(event.replay)return null;
  const locked=Date.now()>=event.startsAt||bout.outcome!=='pending';const n=Number(amount),balance=data?.wallet?.balance??0;const chosen=fighter===bout.blue.id?bout.blue:bout.red;
  async function back(){setBusy(true);setMessage('');try{const r=await fetch('/api/coins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event:event.id,bout:bout.id,fighter:chosen.id,amount:n})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);onReload();window.dispatchEvent(new Event('versus-coins-updated'));setMessage('Fighter backed. Your pick is saved.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save your pick.');}finally{setBusy(false);}}
  if(pick){const name=pick.fighter===bout.red.id?bout.red.name:pick.fighter===bout.blue.id?bout.blue.name:pick.fighter;return <div className={`coin-backing saved ${pick.state}`}><Coins size={15}/><p><strong>{name}</strong> · {pick.amount} coins<span>{pick.state==='pending'?`Awaiting official result · ${pick.amount*2} coin return if correct`:pick.state==='won'?`Correct pick · ${pick.payout} coins returned`:pick.state==='refunded'?`${pick.payout} coins refunded · ${pick.result}`:'Pick settled · 0 coins returned'}</span></p><span className="tag">{pick.state==='pending'?'Backed':pick.state==='won'?'Correct':pick.state==='refunded'?'Refunded':'Settled'}</span></div>;}
  return <div className="coin-backing"><div className="coin-backing-heading"><Coins size={15}/><span>Back with Arena Coins</span><small>Free play</small></div>{locked?<p className="form-hint">Coin picks are locked for this card.</p>:!data?.wallet?<a href="/auth?mode=signup&return_to=%2Ffantasy" className="text-link">Sign up to back a fighter →</a>:<><div className="coin-pick-form"><label className="sr-only" htmlFor={'coin-fighter-'+bout.id}>Fighter to back in bout {bout.id}</label><select id={'coin-fighter-'+bout.id} value={fighter} onChange={e=>setFighter(e.target.value)}><option value={bout.red.id}>{bout.red.name}</option><option value={bout.blue.id}>{bout.blue.name}</option></select><label><span className="sr-only">Coins for bout {bout.id}</span><input aria-label={'Coins for bout '+bout.id} type="number" min={10} max={Math.min(1000,balance)} step={1} value={amount} onChange={e=>setAmount(e.target.value)}/><small>coins</small></label><button className="button outline" disabled={busy||!Number.isInteger(n)||n<10||n>1000||n>balance} onClick={back}>{busy?'Saving…':`Back · ${n||0}`}</button></div><p className="form-hint">{n>=10?`${n*2} coins returned if correct. `:''}One final pick per bout. Minimum 10, maximum 1,000 coins.</p></>}{message&&<p role="status" className="fantasy-message">{message}</p>}</div>;
}
export function CoinHistory({data}:{data:CoinData|null}){if(!data?.wallet)return null;return <section className="panel coin-history"><div className="section-heading"><h2>Your coin activity</h2><Coins size={20}/></div>{data.history.map((row,i)=><div key={row.created+'-'+i}><span>{row.reason}<small>{new Date(row.created).toLocaleString()}</small></span><strong className={row.delta>0?'positive':''}>{row.delta>0?'+':''}{row.delta} coins</strong></div>)}</section>;}
