'use client';
import {useCallback,useEffect,useState} from 'react';
import {Coins,Trophy,RefreshCw,ShieldCheck} from 'lucide-react';
import type {Person} from '../lib/domain';
import {useArena} from './arena-context';
import UserAvatar from './user-avatar';
type Leader=Person&{balance:number;rank:number};type Board={leaders:Leader[];me:Leader|null;total:number;updatedAt:number};
export default function CoinLeaderboardPage(){const{state}=useArena(),[scope,setScope]=useState('all'),[data,setData]=useState<Board|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/leaderboard?scope='+scope,{cache:'no-store'}),d=await r.json() as Board&{error?:string};if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load rankings.');}finally{setLoading(false);}},[scope]);useEffect(()=>{void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);window.addEventListener('versus-coins-updated',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('versus-coins-updated',refresh);};},[load]);
return <><section className="coin-board-hero"><span className="eyebrow"><Trophy size={15}/> THE ARENA COIN LEADERBOARD</span><h1>Who owns<br/><em>the arena?</em></h1><p>The biggest coin balances among real VERSUS accounts. Build your collection, make your reads, climb the board.</p><div className="moments-quick-links"><a href="/moments">Collect & play Moments →</a><a href="/fantasy">Enter fantasy →</a></div></section><div className="coin-board-controls"><div className="shop-filters">{[['all','Everyone'],['friends','Friends']].map(([id,label])=><button key={id} className={scope===id?'selected':''} aria-pressed={scope===id} onClick={()=>{setData(null);setScope(id);}}>{label}</button>)}</div><button className="button ghost" disabled={loading} onClick={load}><RefreshCw size={15}/> {loading?'Refreshing…':'Refresh'}</button></div>{error&&<p className="account-error" role="alert">{error} {scope==='friends'&&!state?.me&&<a href="/auth?return_to=%2Fleaderboard">Sign in</a>}</p>}{data?.me&&<div className="my-coin-rank"><span className="eyebrow">YOUR PLACE</span><strong>#{data.me.rank}</strong><UserAvatar person={data.me}/><span>{data.me.username}</span><b><Coins size={17}/>{data.me.balance.toLocaleString()}</b></div>}{data&&<><div className="coin-board-summary"><span>Top {Math.min(50,data.total)} of {data.total.toLocaleString()} {scope==='friends'?'you and your friends':'accounts'}</span><span>Updated {new Date(data.updatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} · refreshes every 30s</span></div><div className="coin-board-list">{data.leaders.map(person=><a href={'/profile/'+person.id} key={person.id} className={person.id===state?.me.id?'is-me':''}><span className={'coin-board-rank place-'+person.rank}>{person.rank<=3?<Trophy size={20}/>:null}#{person.rank}</span><UserAvatar person={person}/><div><strong>{person.username}{!!person.approved&&<ShieldCheck size={14} aria-label="VERSUS Approved"/>}{person.id===state?.me.id&&<small>YOU</small>}</strong><span>{person.owner?'Arena owner':'Contender'}</span></div><b><Coins size={16}/>{person.balance.toLocaleString()}</b></a>)}</div>{!data.leaders.length&&<div className="empty"><h3>The board is waiting.</h3><p>{scope==='friends'?'Add friends to compare your coin balances.':'Create an account to enter the arena.'}</p><a className="button primary" href={scope==='friends'?'/people':'/auth?mode=signup'}>{scope==='friends'?'Find friends':'Join VERSUS'}</a></div>}</>}<p className="shop-footnote">Ranked by current spendable balance, including welcome coins and owner gifts. Collecting cards, cosmetics, and backing fighters spends coins and can change your place. Equal balances share the same rank. Demo profiles are excluded; blocked connections are hidden from your view. Arena Coins have no cash value.</p></>;
}
