'use client';
import {useEffect,useState} from 'react';
import {Crown,Lock,Plus,Check,Trophy,RefreshCw,ArrowRight,Users} from 'lucide-react';
import {useCoins,CoinWallet,CoinBacking,CoinHistory} from './arena-coins';
import {fantasyRules,scoreLineup,type FantasyEvent,type FantasyFighter,type FantasyLineup} from '../lib/fantasy';
type Entry={user:string;event:string;name:string;username:string;mine:boolean;total:number;settled:number;lineup?:FantasyLineup;rows?:ReturnType<typeof scoreLineup>['rows']};
type Data={events:(FantasyEvent&{syncError:string})[];entries:Entry[];signedIn:boolean};
function useFantasy(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState('');async function reload(){try{const r=await fetch('/api/fantasy',{cache:'no-store'});const d=await r.json() as Data & {error?:string};if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load fantasy cards.');}}useEffect(()=>{reload();const timer=setInterval(reload,60_000);return()=>clearInterval(timer);},[]);return{data,error,reload};}
const formatTime=(t:number)=>new Date(t).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});
function Photo({fighter}:{fighter:FantasyFighter}){const[failed,setFailed]=useState(false);return <div className="fantasy-photo">{fighter.photo&&!failed?<img src={fighter.photo} alt={fighter.name} loading="lazy" onError={()=>setFailed(true)}/>:<span>{fighter.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span>}</div>;}
export default function FantasyPage(){
  const{data,error,reload}=useFantasy();const coins=useCoins();const[selected,setSelected]=useState(''),[drafts,setDrafts]=useState<Record<string,FantasyLineup>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[now,setNow]=useState(Date.now()),[fighterSearch,setFighterSearch]=useState(''),[draftedOnly,setDraftedOnly]=useState(false);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);try{const raw=sessionStorage.getItem('versus-fantasy-pending');if(raw){const pending=JSON.parse(raw) as {event:string;lineup:FantasyLineup};if(pending.event&&Array.isArray(pending.lineup?.fighters)){setSelected(pending.event);setDrafts({[pending.event]:pending.lineup});}sessionStorage.removeItem('versus-fantasy-pending');}}catch{}return()=>clearInterval(t);},[]);
  if(!data)return <section className="panel fantasy-loading"><h1>Fantasy MMA</h1><p>{error||'Getting the fight cards ready…'}</p>{error&&<button className="button outline" onClick={reload}>Try again</button>}</section>;
  const event=data.events.find(e=>e.id===selected)??data.events[0];if(!event)return <section className="panel"><h1>No cards available yet.</h1></section>;
  const mine=data.entries.find(e=>e.event===event.id&&e.mine);const draft=drafts[event.id]??mine?.lineup??{name:'My fight team',fighters:[],captain:''};const locked=!event.replay&&now>=event.startsAt;const available=event.bouts.filter(b=>b.outcome!=='cancelled');const fighters=available.flatMap(b=>[b.red,b.blue]);const cost=draft.fighters.reduce((sum,id)=>sum+(fighters.find(f=>f.id===id)?.cost??0),0);const remaining=fantasyRules.budget-cost;const score=mine?.lineup?scoreLineup(event,mine.lineup):null;const leaderboard=data.entries.filter(e=>e.event===event.id).sort((a,b)=>b.total-a.total);const visibleBouts=available.filter(b=>(!draftedOnly||draft.fighters.includes(b.red.id)||draft.fighters.includes(b.blue.id))&&`${b.red.name} ${b.blue.name} ${b.division}`.toLowerCase().includes(fighterSearch.toLowerCase()));const completed=available.filter(b=>b.outcome!=='pending').length;
  function edit(p:Partial<FantasyLineup>){setDrafts(prev=>({...prev,[event.id]:{...draft,...p}}));setMessage('');}
  function pick(id:string,boutId:string){if(locked)return;const bout=event.bouts.find(b=>b.id===boutId)!;let ids=draft.fighters.filter(x=>x!==bout.red.id&&x!==bout.blue.id);if(!draft.fighters.includes(id)){if(ids.length>=5){setMessage('Your team is full. Remove a fighter to make room.');return;}ids=[...ids,id];}edit({fighters:ids,captain:ids.includes(draft.captain)?draft.captain:ids[0]??''});}
  async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/fantasy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event:event.id,...draft})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await reload();setMessage(event.replay?'Replay saved. Your points are ready.':'Lineup saved. You can change it until the card locks.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save your lineup.');}finally{setBusy(false);}}
  return <><section className="fantasy-intro"><div><span className="eyebrow">ACTUAL UFC EVENTS · FANTASY TEAMS</span><h1>Draft the card.<br/><em>Own fight night.</em></h1><p>Choose five fighters who are scheduled on the selected UFC event. Stay within 60 draft credits, pick a captain, and earn team points from their actual results. Draft credits are a team budget, separate from Arena Coins.</p></div><div className="fantasy-intro-stat"><Crown size={28}/><strong>1.5×</strong><span>Captain points</span></div></section>
    <div className="experience-guide"><div><strong>1 · Draft</strong><p>Pick 5 fighters from 5 different bouts. Save before the event begins.</p></div><div><strong>2 · Watch</strong><p>Your fighters earn team points for real wins and finishes.</p></div><div><strong>3 · Collect</strong><p>Arena Coin picks and played Moments earn coins separately.</p><a href="/moments">Play your Moments →</a></div></div><CoinWallet data={coins.data} error={coins.error} onReload={coins.reload}/><div className="fantasy-event-tabs" aria-label="Choose a fight card">{data.events.map(e=><button aria-pressed={e.id===event.id} className={e.id===event.id?'selected':''} key={e.id} onClick={()=>{setSelected(e.id);setMessage('');}}><span>{e.replay?'REPLAY':e.kind.toUpperCase()}</span><strong>{e.name.replace('UFC Fight Night: ','')}</strong><small>{formatTime(e.startsAt)}</small></button>)}</div>
    <section className="fantasy-event-heading"><div><span className="tag lime">{event.replay?'PAST CARD · PRACTICE':locked?'LINEUPS LOCKED':'DRAFT OPEN'}</span><h2>{event.name}</h2><p>{event.location} · {event.replay?'Replay uses published results. No competitive leaderboard.':`Locks ${formatTime(event.startsAt)} · At the first scheduled prelim`}</p></div><a href={event.source} target="_blank" rel="noreferrer" className="text-link">Official UFC card <ArrowRight size={15}/></a></section>
    {error&&<div className="error-banner" role="alert">{error}<button onClick={reload}>Retry</button></div>}{event.syncError&&<p className="fantasy-sync-warning" role="status">{event.syncError}</p>}
    <div className="fantasy-mobile-summary"><span>{draft.fighters.length}/5 fighters · {remaining} credits left</span><a href="#fantasy-lineup">Your team ↓</a></div><div className="fantasy-layout"><div><div className="section-heading"><h2>The draft board</h2><span className="muted">{available.length} bouts · One fighter per bout</span></div><div className="event-search-tools"><input aria-label="Find fighters on this event" placeholder="Find a fighter or division…" value={fighterSearch} onChange={e=>setFighterSearch(e.target.value)}/><button className="button outline" aria-pressed={draftedOnly} onClick={()=>setDraftedOnly(!draftedOnly)}>{draftedOnly?'Show all bouts':'Show my drafted fighters'}</button></div>{!visibleBouts.length&&<p className="event-empty">No matching fighters. Try another search or show all bouts.</p>}<div className="fantasy-bouts">{visibleBouts.map((bout)=><section className="fantasy-bout" key={bout.id}><div className="fantasy-bout-label"><span>{available.indexOf(bout)===0?'MAIN EVENT':`BOUT ${available.indexOf(bout)+1}`}</span><span>{bout.division}</span>{bout.outcome!=='pending'&&<span className="tag">{bout.method||bout.outcome}</span>}</div><div className="fantasy-bout-pair">{[bout.red,bout.blue].map(f=>{const chosen=draft.fighters.includes(f.id);const disabled=locked||(!chosen&&!draft.fighters.some(id=>id===bout.red.id||id===bout.blue.id)&&draft.fighters.length>=5);return <button className={`fantasy-fighter ${chosen?'drafted':''}`} key={f.id} aria-pressed={chosen} disabled={disabled} onClick={()=>pick(f.id,bout.id)}><Photo fighter={f}/><div><strong>{f.name}</strong><small>{f.cost} credits{bout.winner===f.id?' · Winner':''}</small></div><span className="draft-action">{chosen?<Check size={16}/>:<Plus size={16}/>}</span></button>;})}</div><CoinBacking event={event} bout={bout} data={coins.data} onReload={coins.reload}/></section>)}</div></div>
    <aside><section id="fantasy-lineup" className="panel fantasy-team"><div className="section-heading"><div><span className="eyebrow">YOUR FIGHT TEAM</span><h2>{locked?'The lineup is locked.':'Build a winning corner.'}</h2></div>{locked?<Lock size={20}/>:<Crown size={20}/>}</div><div className="fantasy-budget"><div><small>FIGHTERS</small><strong>{draft.fighters.length}<span>/ 5</span></strong></div><div className={remaining<0?'over-budget':''}><small>CREDITS LEFT</small><strong>{remaining}<span>/ 60</span></strong></div></div><label className="fantasy-team-name">Team name<input disabled={locked} required minLength={3} maxLength={36} value={draft.name} onChange={e=>edit({name:e.target.value})}/></label><div className="fantasy-slots">{Array.from({length:5},(_,i)=>{const id=draft.fighters[i];const f=fighters.find(f=>f.id===id)??event.bouts.flatMap(b=>[b.red,b.blue]).find(f=>f.id===id);return f?<div className="fantasy-slot filled" key={id}><Photo fighter={f}/><div><strong>{f.name}</strong><small>{f.cost} credits{!fighters.some(x=>x.id===id)?' · Withdrawn':''}</small></div><button disabled={locked} className={draft.captain===id?'captain active':'captain'} aria-label={`Make ${f.name} captain`} aria-pressed={draft.captain===id} onClick={()=>edit({captain:id})}><Crown size={17}/></button>{!locked&&<button aria-label={`Remove ${f.name}`} className="remove-draft" onClick={()=>{const ids=draft.fighters.filter(x=>x!==id);edit({fighters:ids,captain:ids.includes(draft.captain)?draft.captain:ids[0]??''});}}>×</button>}</div>:<div className="fantasy-slot" key={'empty'+i}><span>{i+1}</span><p>Draft a fighter</p></div>;})}</div><p className="form-hint"><Crown size={13}/> Choose your captain using the crown. All their points get a 1.5× boost.</p>{data.signedIn?<button className="button primary" disabled={busy||locked||draft.fighters.length!==5||remaining<0||draft.name.trim().length<3} onClick={save}>{busy?'Saving…':locked?'Locked':event.replay?'Score my replay':mine?'Save lineup changes':'Enter this card'}</button>:<a className="button primary" onClick={()=>{try{sessionStorage.setItem('versus-fantasy-pending',JSON.stringify({event:event.id,lineup:draft}));}catch{}}} href="/auth?mode=signup&return_to=%2Ffantasy">Join VERSUS to save your team</a>}{message&&<p className="fantasy-message" role="status">{message}</p>}{mine&&<p className="form-hint">Saved lineup · {event.replay?'Practice mode':locked?'Ready for results':'Editable until lock'}</p>}</section>
    <section className="panel fantasy-rules"><h3>Every finish counts.</h3>{[['Win','+30'],['KO / TKO or submission','+20'],['Submission bonus','+5'],['Round 1 finish','+10'],['Round 2 finish','+5'],['Draw','+10'],['Captain','1.5×']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}<p className="form-hint">Bonuses stack. Losses, no contests, cancellations, and withdrawals score 0. Disqualification wins get win points only. Credits follow official ranking tiers, not betting odds.</p></section></aside></div>
    {score&&<section className="panel fantasy-results"><div className="section-heading"><div><span className="eyebrow">{event.replay?'REPLAY SCORE':'YOUR CARD SCORE'}</span><h2>{mine!.name}</h2></div><strong className="fantasy-total">{score.total}<small>pts</small></strong></div><p className="muted">{score.settled}/5 drafted fighters settled · {completed}/{available.length} card bouts settled</p>{score.rows.map(r=><div className="fantasy-result-row" key={r.id}><strong>{r.name}{r.captain&&<Crown size={14}/>}</strong><span>{r.parts.join(' · ')}{r.captain?' · Captain ×1.5':''}</span><b>{r.points} pts</b></div>)}</section>}
    <section className="panel fantasy-leaderboard"><div className="section-heading"><div><span className="eyebrow">{event.replay?'PRACTICE CORNER':'CARD LEADERBOARD'}</span><h2>{event.replay?'Explore a finished card.':'The whole arena is competing.'}</h2></div><Users size={22}/></div>{event.replay?<p className="muted">Replay lineups stay private and never count toward competitive totals. Try different picks and see how finish bonuses change your score.</p>:<><p className="muted">{locked?'Standings update as verified results arrive. Equal scores share a rank.':`${leaderboard.length} teams entered. Opponents’ lineups stay hidden until lock.`}</p>{leaderboard.length?<div>{leaderboard.map((entry,i)=><div className={`fantasy-standing ${entry.mine?'mine':''}`} key={entry.user}><strong>{locked?leaderboard.findIndex(e=>e.total===entry.total)+1:'—'}</strong><div><a href={'/profile/'+entry.user}>{entry.username}{entry.mine?' · You':''}</a><span>{entry.name}{entry.lineup?' · '+entry.lineup.fighters.map(id=>fighters.find(f=>f.id===id)?.name??id).join(', '):''}</span></div><b>{locked?`${entry.total} pts`:'Entered'}</b></div>)}</div>:<p className="fantasy-empty">No teams yet. Take the first corner.</p>}</>}</section>
    <CoinHistory data={coins.data}/><p className="fantasy-source"><RefreshCw size={14}/> Card verified {formatTime(event.checkedAt)}. Official results are checked every five minutes around fight night and may arrive late. Cards can change. Existing draft prices stay fixed. <a href={event.source} target="_blank" rel="noreferrer">UFC source</a> · Free play · No real-money wagering.</p></>;
}
export function FantasyProfile(){const{data}=useFantasy();const own=data?.entries.filter(e=>e.mine&&!data.events.find(c=>c.id===e.event)?.replay)??[];return <section className="panel fantasy-profile-summary"><div><span className="eyebrow">FANTASY MMA</span><h3>Your fight-night corner</h3><p>{own.length} event {own.length===1?'lineup':'lineups'} · {own.reduce((n,e)=>n+e.total,0)} points from official results</p></div><a className="button outline" href="/fantasy">Draft a fight team <ArrowRight size={16}/></a></section>;}
