'use client';
import {useCallback,useEffect,useState} from 'react';
import {Coins,Sparkles,Check,Lock,Trophy,RefreshCw,Search} from 'lucide-react';
import {moments,type Moment,type MomentPlay,validateMomentPlays} from '../lib/moments';
import type {FantasyEvent} from '../lib/fantasy';
import photos from '../lib/fighter-photos.json';
import scenes from '../lib/fighter-scenes.json';
import seeds from '../lib/fantasy-events.json';
type Collection={balance:number|null;owned:string[];plays:MomentPlay[];events:(FantasyEvent&{syncError?:string})[]};
const photoMap:Record<string,{url:string}>=photos;
export function MomentArt({card,small=false}:{card:Moment;small?:boolean}){const[failed,setFailed]=useState(0);const scene=(scenes as Record<string,{url:string;event:string|null;source:string}[]>)[card.portrait]?.find(s=>s.event===card.event);const photo=photoMap[card.portrait]?.url??seeds.flatMap(e=>e.bouts.flatMap(b=>[b.red,b.blue])).find(f=>f.id===card.fighter)?.photo;const candidates=[scene?.url,photo].filter((url):url is string=>!!url),image=candidates[failed];return <div className={'moment-art '+(small?'mini':'')+' '+(scene&&image===scene.url?'has-scene':'')} style={{'--moment-color':card.color} as React.CSSProperties}><span className="moment-serial">VERSUS / MOMENTS</span>{image&&<img src={image} alt={`${card.name} · ${card.event}`} loading="lazy" onError={()=>setFailed(n=>n+1)}/>}<span className="moment-tier">{card.tier}</span><div className="moment-art-title"><span>{card.event}</span><h3>{card.title}</h3><p>{card.name}</p></div></div>;}
export default function MomentsPage(){const[limit,setLimit]=useState(24),[data,setData]=useState<Collection|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(''),[filter,setFilter]=useState('all'),[q,setQ]=useState(''),[eventId,setEventId]=useState(''),[draft,setDraft]=useState<string[]>([]),[dirty,setDirty]=useState(false),[now,setNow]=useState(Date.now());
useEffect(()=>setLimit(24),[q,filter]);
useEffect(()=>{const params=new URLSearchParams(location.search);setQ(params.get('q')??'');if(params.get('owned')==='1')setFilter('owned');},[]);
const load=useCallback(async()=>{try{const r=await fetch('/api/moments',{cache:'no-store'}),d=await r.json() as Collection&{error?:string};if(!r.ok)throw Error(d.error);setData(d);setError('');setEventId(old=>old||d.events.find((e:FantasyEvent)=>!e.replay&&e.startsAt>Date.now())?.id||d.events.find((e:FantasyEvent)=>!e.replay)?.id||'');}catch(e){setError(e instanceof Error?e.message:'Could not load Moments.');}},[]);
useEffect(()=>{void load();const tick=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(tick);},[load]);
useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')void load();};window.addEventListener('focus',refresh);const timer=setInterval(refresh,60000);return()=>{window.removeEventListener('focus',refresh);clearInterval(timer);};},[load]);
useEffect(()=>{if(!dirty)setDraft(data?.plays.filter(p=>p.event===eventId).sort((a,b)=>a.slot-b.slot).map(p=>p.card)??[]);},[data,eventId,dirty]);
const event=data?.events.find(e=>e.id===eventId),locked=!!event&&now>=event.startsAt;
useEffect(()=>{if(locked)setDirty(false);},[locked]);
async function act(body:Record<string,unknown>,key:string){setBusy(key);setMessage('');try{const r=await fetch('/api/moments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);if(key==='lineup')setDirty(false);await load();window.dispatchEvent(new Event('versus-coins-updated'));setMessage(key==='lineup'?'Your Moments lineup is saved. It locks when the event starts.':'Moment collected. It is yours to keep and play again.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save.');}finally{setBusy('');}}
function toggle(card:Moment){if(!data||!event)return;const next=draft.includes(card.id)?draft.filter(id=>id!==card.id):[...draft,card.id];const problem=validateMomentPlays(event,next,data.owned);if(problem){setMessage(problem);return;}setDraft(next);setDirty(true);setMessage('');}
const visible=moments.filter(m=>(filter!=='owned'||data?.owned.includes(m.id))&&(filter!=='available'||event?.bouts.some(b=>b.outcome==='pending'&&(b.red.id===m.fighter||b.blue.id===m.fighter)))&&`${m.name} ${m.title} ${m.event}`.toLowerCase().includes(q.toLowerCase()));const plays=data?.plays.filter(p=>p.event===eventId)??[];const earned=data?.plays.reduce((n,p)=>n+p.payout,0)??0;
return <><section className="moments-hero"><div><span className="eyebrow"><Sparkles size={15}/> THE MOMENTS COLLECTION · {moments.length} CARDS · {new Set(moments.map(m=>m.portrait)).size} FIGHTERS</span><h1>Some seconds<br/><em>last forever.</em></h1><p>Collect the finishes, comebacks, and nights that made UFC history. Then put your collection into play.</p><div className="moments-quick-links"><a href="/leaderboard"><Trophy size={15}/> Coin leaderboard →</a><a href="/shop">Profile shop →</a></div></div><div className="moments-featured"><MomentArt card={moments.find(m=>m.id==='holloway-last-second')!}/></div></section><div className="moment-stats"><div><Coins size={20}/><strong>{data?.balance?.toLocaleString()??'—'}</strong><span>YOUR COINS</span></div><div><Sparkles size={20}/><strong>{data?.owned.length??0} / {moments.length}</strong><span>COLLECTED</span></div><div><Trophy size={20}/><strong>+{earned.toLocaleString()}</strong><span>MOMENTS REWARDS</span></div></div>{error&&<p className="account-error" role="alert">{error} <button onClick={load}>Retry</button></p>}{!data&& !error&&<p role="status">Loading your collection…</p>}{data?.balance===null&&<div className="shop-signin"><Lock size={18}/><p>Sign in to collect Moments and save your lineup.</p><a className="button primary" href="/auth?return_to=%2Fmoments">Sign in</a></div>}
<section className="moment-play-panel" id="lineup"><div className="moment-play-heading"><div><span className="eyebrow">PLAY YOUR COLLECTION</span><h2>Your next fight night.</h2><p>Up to 3 owned Moments. Different fighters, different bouts. Reuse your cards every event.</p></div><button className="button ghost" disabled={!!busy} onClick={load}><RefreshCw size={15}/> Refresh results</button></div><label className="moment-event-label">Official event<select value={eventId} onChange={e=>{setDirty(false);setEventId(e.target.value);setMessage('');}}>{data?.events.filter(e=>!e.replay).map(e=><option key={e.id} value={e.id}>{e.name}{now>=e.startsAt?' · Locked':''}</option>)}</select></label>{event&&<p className="moment-lock-note">{locked?<><Lock size={14}/> Lineup locked · official results earn coins automatically</>:<>Locks {new Date(event.startsAt).toLocaleString()} · Save before the event starts</>}</p>}{event?.syncError&&<p className="muted small-text">{event.syncError}</p>}<div className="moment-slots">{Array.from({length:3},(_,i)=>{const card=moments.find(m=>m.id===draft[i]),play=plays.find(p=>p.card===card?.id);return <div key={i} className={'moment-slot '+(card?'filled':'')}><span className="eyebrow">SLOT 0{i+1}</span>{card?<><strong>{card.name}</strong><span>{card.title}</span>{locked?<b>{play?.state==='settled'?`${play.result} · +${play.payout} coins`:'Awaiting official result'}</b>:<button className="text-link" disabled={!!busy} onClick={()=>toggle(card)}>Remove</button>}</>:<><Sparkles size={24}/><span>{locked?'No Moment played':'Choose a card below'}</span></>}</div>;})}</div><div className="moment-rules"><span>Win <b>+40</b></span><span>KO / TKO / submission <b>+25</b></span><span>Round-one finish <b>+15</b></span></div><div className="moment-save-row"><p>Up to 80 coins per played Moment. Losses, draws, no contests, and cancellations earn 0. Cards are kept.</p><button className="button primary" disabled={!data||data.balance===null||locked||!event||!dirty||!!busy} onClick={()=>act({action:'lineup',event:eventId,cards:draft},'lineup')}>{busy==='lineup'?'Saving…':locked?'Locked':dirty?'Save lineup':draft.length?'Lineup saved':'Choose Moments'}</button></div>{dirty&&!locked&&<p className="moment-unsaved">Unsaved changes — save your lineup to earn rewards.</p>}</section>
{message&&<p className="shop-status" role="status">{message}</p>}<div className="shop-section-head"><div><h2>Build a collection worth remembering.</h2><p>Fixed prices. No random packs. Every tier earns the same performance rewards.</p></div></div><div className="moment-tools"><div className="shop-filters">{[['all','All Moments'],['owned','My collection'],['available','On this event']].map(([id,name])=><button key={id} aria-pressed={filter===id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{name}</button>)}</div><label className="moment-search"><Search size={16}/><input aria-label="Search Moments" placeholder="Fighter, moment, event…" value={q} onChange={e=>setQ(e.target.value)}/></label></div><div className="moments-grid">{visible.slice(0,limit).map(card=>{const owned=data?.owned.includes(card.id),selected=draft.includes(card.id),available=event?.bouts.some(b=>b.outcome==='pending'&&(b.red.id===card.fighter||b.blue.id===card.fighter));return <article className="collectible-moment" key={card.id}><MomentArt card={card}/><div className="moment-card-body"><span className="moment-date">{card.date}{owned&&<b><Check size={12}/> Collected</b>}</span><p>{card.story}</p><a className="moment-source" href={card.source} target="_blank" rel="noreferrer">View official fight source ↗</a><div className="moment-card-actions"><span><Coins size={15}/>{card.price}</span>{data?.balance==null?<a className="button outline" href="/auth?return_to=%2Fmoments">Sign in</a>:!owned?<button className="button primary" disabled={!!busy||data.balance<card.price} onClick={()=>act({action:'buy',card:card.id},card.id)}>{busy===card.id?'Collecting…':data.balance<card.price?'Need coins':'Collect'}</button>:<button className={'button '+(selected?'primary':'outline')} disabled={!!busy||locked||!available} onClick={()=>toggle(card)}>{selected?'In lineup ✓':locked?'Event locked':available?'Play Moment':'Not on card'}</button>}</div></div></article>;})}</div>{visible.length>limit&&<button className="button outline back-top" onClick={()=>setLimit(n=>n+24)}>Show more Moments ({Math.min(limit,visible.length)} of {visible.length})</button>}{!visible.length&&<div className="empty"><h3>{filter==='owned'?'Your collection starts here.':'No matching Moments.'}</h3><p>{filter==='owned'?'Collect a card with Arena Coins to play it on future events.':'Try another search or event. Fighters must be scheduled on the selected official card.'}</p></div>}
{!!data?.plays.some(p=>p.state==='settled')&&<section className="moment-history panel"><h2>Your reward history</h2>{data.plays.filter(p=>p.state==='settled').slice(0,12).map(p=><div key={p.event+':'+p.slot}><span><strong>{moments.find(m=>m.id===p.card)?.title}</strong><small>{data.events.find(e=>e.id===p.event)?.name??p.event} · {p.result}</small></span><b>+{p.payout} coins</b></div>)}</section>}<p className="shop-footnote">Independent fan collectibles, not official UFC merchandise. Fighter portraits: UFC. Historic moments celebrate past results; rewards only apply to lineups saved before future tracked events. Replays never pay coins. Arena Coins have no cash value and cannot be sold, traded, or cashed out.</p></>;
}
