'use client';
import {useEffect,useState} from 'react';
import {Search,Users,RefreshCw,ShieldCheck} from 'lucide-react';
import type {Person} from '../lib/domain';
import {useArena} from './arena-context';
import {useSocial,type SocialState} from './social-context';
import UserAvatar from './user-avatar';
import FriendActions from './social-actions';
import {ApprovedBadge} from './owner-panel';
const tabs=['Find accounts','Friends','Requests','Following','Blocked'] as const;
export default function PeoplePage(){const{state,loading:arenaLoading}=useArena();const social=useSocial();const[tab,setTab]=useState<typeof tabs[number]>('Find accounts');const[q,setQ]=useState('');const[sort,setSort]=useState('name');const[offset,setOffset]=useState(0);const[people,setPeople]=useState<Person[]>([]);const[more,setMore]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const me=state?.me.id;
useEffect(()=>{const value=new URLSearchParams(window.location.search).get('tab');const initial=value==='requests'?'Requests':value==='friends'?'Friends':value==='following'?'Following':value==='blocked'?'Blocked':null;if(initial)setTab(initial);},[]);
useEffect(()=>{if(!me||tab!=='Find accounts')return;const controller=new AbortController();const timer=setTimeout(async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/social?q=${encodeURIComponent(q)}&sort=${sort}&offset=${offset}`,{signal:controller.signal,cache:'no-store'});const d=await r.json() as SocialState&{error?:string};if(!r.ok)throw Error(d.error);setPeople(d.people);setMore(d.hasMore);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not search accounts.');}finally{if(!controller.signal.aborted)setLoading(false);}},250);return()=>{clearTimeout(timer);controller.abort();};},[q,sort,offset,me,tab,social.data]);
if(arenaLoading)return <p>Loading your community…</p>;if(!me)return <section className="panel"><h1>Find your people.</h1><p>Sign in to search accounts, send requests, and build your friends list.</p><a className="button primary" href="/auth?return_to=%2Fpeople">Sign in</a></section>;
const relationships=social.data?.relationships??[],contacts=social.data?.contacts??[];const friends=relationships.filter(r=>r.state==='accepted');const incoming=relationships.filter(r=>r.state==='pending'&&r.requester!==me);const outgoing=relationships.filter(r=>r.state==='pending'&&r.requester===me);const match=(p:Person)=>p.username.toLowerCase().includes(q.trim().toLowerCase());const contactFor=(r:typeof relationships[number])=>contacts.find(p=>p.id===(r.low===me?r.high:r.low));const friendPeople=friends.map(contactFor).filter((p):p is Person=>!!p).filter(match);const following=(state?.users??[]).filter(p=>p.id!==me&&state?.follows.some(f=>f.user===me&&f.target===p.id)).filter(match);
function card(p:Person){return <article className="panel person-card" key={p.id}><a className="person-card-identity" href={'/profile/'+p.id}><UserAvatar person={p} large/><div><h3>{p.username}</h3>{!!p.approved&&<ApprovedBadge small/>}{!!p.earlySupporter&&<span className="micro-tag">Early Supporter</span>}<p>{p.bio||'Ready for the next great matchup.'}</p>{p.location&&<small>{p.location}</small>}</div></a><div className="person-card-actions"><FriendActions target={p.id}/><a className="text-link" href={'/profile/'+p.id}>View profile →</a></div></article>;}
const empty=(message:string)=><div className="social-empty"><Users size={36}/><h3>{message}</h3><p>{q?'Try another username or clear your search.':'Find an account and send your first friend request.'}</p>{tab!=='Find accounts'&&<button className="button outline" onClick={()=>{setTab('Find accounts');setQ('');setOffset(0);}}>Find accounts</button>}</div>;
return <div className="people-page"><div className="section-heading"><div><span className="eyebrow">YOUR PEOPLE, YOUR ARENA</span><h1>Find your corner.</h1><p>Look up accounts. Add friends. Make fight night a shared experience.</p></div><button className="button outline" disabled={social.busy} onClick={()=>social.refresh()}><RefreshCw size={15}/> Refresh</button></div><div className="social-stats"><span><strong>{friends.length}</strong> friends</span><span><strong>{incoming.length}</strong> incoming requests</span><span><strong>{outgoing.length}</strong> requests sent</span></div><div className="social-tabs" role="tablist" aria-label="Account directory">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'selected':''} onClick={()=>{setTab(t);setOffset(0);}}>{t}{t==='Requests'&&incoming.length>0&&<span className="request-count">{incoming.length}</span>}</button>)}</div><div className="people-search"><label><Search size={19}/><span className="sr-only">Search usernames</span><input value={q} maxLength={24} placeholder="Search a username…" autoComplete="off" autoCapitalize="none" spellCheck={false} onChange={e=>{setQ(e.target.value);setOffset(0);}}/>{q&&<button className="text-link" onClick={()=>{setQ('');setOffset(0);}}>Clear</button>}</label>{tab==='Find accounts'&&<label><span className="sr-only">Sort accounts</span><select value={sort} onChange={e=>{setSort(e.target.value);setOffset(0);}}><option value="name">Username A–Z</option><option value="newest">Newest accounts</option></select></label>}</div>{(error||social.error)&&<p role="alert" className="account-error">{error||social.error}</p>}
{tab==='Find accounts'&&(loading?<p className="social-empty" role="status">Searching accounts…</p>:<><div className="people-grid">{people.map(card)}</div>{!people.length&&empty('No matching accounts yet.')}<div className="people-pagination">{offset>0&&<button className="button outline" onClick={()=>setOffset(Math.max(0,offset-24))}>← Previous</button>}{more&&<button className="button outline" onClick={()=>setOffset(offset+24)}>Next accounts →</button>}</div></>)}
{tab==='Friends'&&<><div className="people-grid">{friendPeople.map(card)}</div>{!friendPeople.length&&empty('Your friends list starts here.')}</>}
{tab==='Following'&&<><p className="muted">Following is separate from friendship. Friends accept each other’s requests.</p><div className="people-grid">{following.map(card)}</div>{!following.length&&empty('No followed accounts match.')}</>}
{tab==='Requests'&&<><h2>Received</h2><div className="people-grid">{incoming.map(contactFor).filter((p):p is Person=>!!p).filter(match).map(card)}</div>{!incoming.map(contactFor).some(p=>p&&match(p))&&<p className="muted">No incoming requests match.</p>}<h2>Sent</h2><div className="people-grid">{outgoing.map(contactFor).filter((p):p is Person=>!!p).filter(match).map(card)}</div>{!outgoing.map(contactFor).some(p=>p&&match(p))&&<p className="muted">No outgoing requests match.</p>}</>}
{tab==='Blocked'&&<><div className="social-privacy-note"><ShieldCheck size={18}/><p>Blocked accounts cannot send you friend requests or follow you. Blocking removes your friendship and follows between both accounts. Public discussions remain visible.</p></div><div className="people-grid">{social.data?.blocked.filter(match).map(card)}</div>{!social.data?.blocked.some(match)&&<p className="muted">No blocked accounts match.</p>}</>}
</div>;}
