'use client';
import {useCallback,useEffect,useState} from 'react';
import {moments} from '../lib/moments';
import {MomentArt} from './moments-page';
type Data={cards:string[];caption:string;mine:boolean;owned:string[]};
export default function ProfileShowcase({user,mine}:{user:string;mine:boolean}){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[editing,setEditing]=useState(false),[cards,setCards]=useState<string[]>([]),[caption,setCaption]=useState(''),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=useCallback(async()=>{try{const r=await fetch('/api/showcase?user='+encodeURIComponent(user),{cache:'no-store'}),d=await r.json() as Data & {error?:string};if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Showcase unavailable.');}},[user]);
 useEffect(()=>{setData(null);setEditing(false);void load();},[load]);
 function edit(){setCards(data?.cards??[]);setCaption(data?.caption??'');setQ('');setMessage('');setEditing(true);}
 function move(i:number,d:number){const next=[...cards];[next[i],next[i+d]]=[next[i+d],next[i]];setCards(next);}
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/showcase',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cards,caption})}),d=await r.json() as Data & {error?:string};if(!r.ok)throw Error(d.error);await load();setEditing(false);setMessage('Your card showcase is saved. Everyone visiting your profile can see it.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 const shown=(editing?cards:data?.cards??[]).map(id=>moments.find(m=>m.id===id)).filter((m):m is typeof moments[number]=>!!m),owned=moments.filter(m=>data?.owned.includes(m.id)&&`${m.name} ${m.title} ${m.event}`.toLowerCase().includes(q.toLowerCase()));
 return <section className="panel profile-showcase" id="card-showcase"><div className="section-heading"><div><span className="eyebrow">YOUR COLLECTION, ON DISPLAY</span><h2>Card showcase</h2><p>{(editing?caption:data?.caption)||'Six spots for the moments that mean the most.'}</p></div>{mine&&data&&!editing&&<button className="button outline" onClick={edit}>Customize showcase</button>}</div>{error&&<p role="alert">{error} <button onClick={load}>Retry</button></p>}{!data&&!error&&<p role="status">Loading showcase…</p>}{mine&&data&&<p className="archive-note">{data.owned.length} {data.owned.length===1?'card':'cards'} collected · {editing?cards.length:data.cards.length}/6 {editing?'selected':'displayed'} · <a href="/moments?owned=1">Open your collection →</a></p>}
 <div className="showcase-grid">{shown.map((card,i)=><article key={card.id}><a href={'/moments?q='+encodeURIComponent(card.name)} aria-label={`View ${card.name}: ${card.title}`}><MomentArt card={card} small/></a>{editing&&<div className="showcase-order"><button aria-label={'Move '+card.name+' left'} disabled={i===0||busy} onClick={()=>move(i,-1)}>←</button><span>Spot {i+1}</span><button aria-label={'Move '+card.name+' right'} disabled={i===cards.length-1||busy} onClick={()=>move(i,1)}>→</button><button disabled={busy} aria-label={'Remove '+card.name+' from showcase'} onClick={()=>setCards(cards.filter(c=>c!==card.id))}>Remove</button></div>}</article>)}</div>
 {data&&!shown.length&&<div className="showcase-empty"><h3>{mine?'Make your collection part of your identity.':'No cards displayed yet.'}</h3><p>{mine?'Collect a Moment, then pin it here. Your cards stay in your collection.':'This fighter fan has not pinned any Moments.'}</p>{mine&&<a className="button outline" href="/moments">Explore Moments →</a>}</div>}
 {editing&&<div className="showcase-editor"><label>Showcase caption<input maxLength={80} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="My favorite nights in the Octagon…"/></label><label>Find an owned card<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search your cards…"/></label><p className="archive-note">Choose up to six. Use the arrows above to arrange them. Changes are previews until you save. This display never locks cards or changes a fight-night lineup.</p><div className="showcase-picker">{owned.map(m=><button key={m.id} aria-pressed={cards.includes(m.id)} disabled={busy||(!cards.includes(m.id)&&cards.length===6)} onClick={()=>setCards(cards.includes(m.id)?cards.filter(c=>c!==m.id):[...cards,m.id])}><strong>{m.name}</strong><span>{m.title} · {m.event}</span><b>{cards.includes(m.id)?'Selected ✓':'+ Display'}</b></button>)}</div>{!owned.length&&<p>{data?.owned.length?'No matching cards.':'Your collection is empty. Collect your first Moment to display it here.'}</p>}<div className="showcase-save"><button className="button primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save showcase'}</button><button className="button outline" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></div></div>}{message&&<p role="status">{message}</p>}</section>;
}

