'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {Upload,Trash2,Move,RotateCcw} from 'lucide-react';
import type {Person} from '../lib/domain';
import {useArena} from './arena-context';
import {photoCrop} from '../lib/photo-crop';
export default function ProfilePhotoUpload({person,disabled=false,onChange,onBusyChange}:{person:Person;disabled?:boolean;onChange?:(avatar:string)=>void;onBusyChange?:(busy:boolean)=>void}){
 const id=useId(),{reload}=useArena(),canvas=useRef<HTMLCanvasElement>(null),bitmap=useRef<ImageBitmap|null>(null),drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 const[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[zoom,setZoom]=useState(1),[x,setX]=useState(0),[y,setY]=useState(0),[message,setMessage]=useState(''),[error,setError]=useState('');
 function pending(value:boolean){setBusy(value);onBusyChange?.(value);}
 useEffect(()=>()=>bitmap.current?.close(),[]);
 useEffect(()=>{const image=bitmap.current,ctx=canvas.current?.getContext('2d');if(!image||!ctx)return;const crop=photoCrop(image.width,image.height,zoom,x,y);ctx.fillStyle='#18212b';ctx.fillRect(0,0,512,512);ctx.drawImage(image,crop.x,crop.y,crop.side,crop.side,0,0,512,512);},[editing,zoom,x,y,revision]);
 async function choose(file:File){pending(true);setError('');setMessage('');try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Choose a JPG, PNG, or WebP under 5 MB.');let image:ImageBitmap;try{image=await createImageBitmap(file);}catch{throw Error('This image could not be opened. Try another photo.');}if(image.width*image.height>32000000){image.close();throw Error('Choose an image under 32 megapixels.');}bitmap.current?.close();bitmap.current=image;drag.current=null;setRevision(n=>n+1);setZoom(1);setX(0);setY(0);setEditing(true);}catch(e){setError(e instanceof Error?e.message:'Could not open photo.');}finally{pending(false);}}
 function cancel(){bitmap.current?.close();bitmap.current=null;setEditing(false);setError('');setMessage('Photo changes cancelled. Your saved picture is unchanged.');}
 async function save(){if(!canvas.current)return;pending(true);setError('');setMessage('');try{const blob=await new Promise<Blob>((resolve,reject)=>canvas.current!.toBlob(b=>b?resolve(b):reject(Error('Could not prepare your photo.')),'image/jpeg',0.82));if(blob.size>200000)throw Error('Choose a simpler or smaller photo.');const response=await fetch('/api/profile-photo',{method:'POST',headers:{'Content-Type':'image/jpeg'},body:blob});const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error??'Could not save photo.');await reload();onChange?.('upload');bitmap.current?.close();bitmap.current=null;setEditing(false);setMessage('Your adjusted profile picture is saved.');}catch(e){setError(e instanceof Error?e.message:'Could not save photo.');}finally{pending(false);}}
 async function remove(){pending(true);setError('');setMessage('');try{const response=await fetch('/api/profile-photo',{method:'DELETE'});const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error??'Could not remove photo.');await reload();onChange?.(person.avatar==='upload'?'initials':person.avatar??'initials');setMessage('Uploaded photo removed.');}catch(e){setError(e instanceof Error?e.message:'Could not remove photo.');}finally{pending(false);}}
 return <div className="profile-upload"><input id={id} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" disabled={disabled||busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void choose(file);}}/><label htmlFor={id} className={`button outline upload-file-button ${disabled||busy?'is-disabled':''}`}><Upload size={17}/>{busy?'Preparing photo…':person.photoUpdated?'Change uploaded photo':'Upload your own photo'}</label><small>JPG, PNG, or WebP · Up to 5 MB. Position and zoom your photo before saving.</small>{editing&&<section className="photo-editor" aria-label="Adjust profile picture"><h3>Make it fit your corner.</h3><p><Move size={14}/> Drag the photo, or use the sliders below.</p><canvas ref={canvas} width={512} height={512} aria-label="Profile photo crop preview" onPointerDown={e=>{if(busy)return;drag.current={x:e.clientX,y:e.clientY,left:x,top:y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const start=drag.current,image=bitmap.current;if(!start||!image||busy)return;const rect=e.currentTarget.getBoundingClientRect(),side=Math.min(image.width,image.height)/zoom;const clamp=(n:number)=>Math.max(-100,Math.min(100,n));if(image.width>side)setX(clamp(start.left-(e.clientX-start.x)/rect.width*side/(image.width-side)*200));if(image.height>side)setY(clamp(start.top-(e.clientY-start.y)/rect.height*side/(image.height-side)*200));}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/><label>Zoom <output>{zoom.toFixed(1)}×</output><input type="range" min={1} max={4} step={0.05} value={zoom} disabled={busy} onChange={e=>setZoom(Number(e.target.value))}/></label><label>Horizontal position<input type="range" min={-100} max={100} value={x} disabled={busy} onChange={e=>setX(Number(e.target.value))}/></label><label>Vertical position<input type="range" min={-100} max={100} value={y} disabled={busy} onChange={e=>setY(Number(e.target.value))}/></label><div className="photo-editor-actions"><button type="button" className="button ghost" disabled={busy} onClick={()=>{setZoom(1);setX(0);setY(0);}}><RotateCcw size={14}/> Reset</button><button type="button" className="button outline" disabled={busy} onClick={cancel}>Cancel</button><button type="button" className="button primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save photo'}</button></div><small>Your picture changes only when you press Save photo.</small></section>}{!!person.photoUpdated&&!editing&&<button type="button" className="text-link upload-remove" disabled={disabled||busy} onClick={remove}><Trash2 size={14}/> Remove uploaded photo</button>}{error&&<p className="account-error" role="alert">{error}</p>}{message&&<p className="upload-success" role="status">{message}</p>}</div>;
}
