'use client';
import {UserRound,MessageSquare,Target,ArrowUp,ArrowDown,X} from 'lucide-react';
import type {Competitor,Matchup,Debate} from '../lib/domain';
import {competitor} from '../lib/competitors';
import {overall,probability} from '../lib/ratings';
import {sampleDebates,samplePeople} from '../lib/community';
import {useArena} from './arena-context';
import {useState} from 'react';
import photos from '../lib/fighter-photos.json';
import UserAvatar from './user-avatar';
const photoMap:Record<string,{url:string}>=photos;
export function Portrait({c,large=false}:{c:Competitor;large?:boolean}){const[failed,setFailed]=useState(false);const image=photoMap[c.id]?.url;return <div className={`portrait ${large?'large':''} ${image&&!failed?'has-photo':''}`} style={{'--fighter-color':c.color} as React.CSSProperties}>{image&&!failed?<img src={image} alt={c.name} loading={large?'eager':'lazy'} decoding="async" onError={()=>setFailed(true)}/>:<><UserRound strokeWidth={.8}/><span className="portrait-initials">{c.initials}</span></>}<span className="portrait-label">{c.flag}</span></div>}
export function Head({eyebrow,title,subtitle,children}:{eyebrow:string;title:string;subtitle?:string;children?:React.ReactNode}){return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{children}</div>}
export function Empty({title,body,children}:{title:string;body:string;children?:React.ReactNode}){return <div className="empty"><Target/><h3>{title}</h3><p>{body}</p>{children}</div>}
export function Score({c}:{c:Competitor}){return <span className="score" style={{color:c.color}}>{overall(c).toFixed(1)}</span>}
export function MatchCard({m}:{m:Matchup}){const a=competitor(m.a),b=competitor(m.b);const{state}=useArena();const debateCount=[...sampleDebates,...(state?.debates??[])].filter(d=>d.matchup===m.id).length;return <a className="match-card" href={`/matchup/${m.id}`}><div className="card-top"><span>{m.label}</span><span>{a.division===b.division?a.division:'Fantasy · P4P'}</span></div><div className="card-versus"><div><Portrait c={a}/><strong>{a.name.split(' ').at(-1)}</strong><small>{a.record.join('-')}</small></div><span className="vs">VS</span><div><Portrait c={b}/><strong>{b.name.split(' ').at(-1)}</strong><small>{b.record.join('-')}</small></div></div><div className="card-meter"><i style={{width:`${probability(a,b)}%`,background:a.color}}/><i style={{flex:1,background:b.color}}/></div><div className="card-bottom"><span><MessageSquare size={14}/>{debateCount} arguments</span><span>Compare matchup</span></div></a>}
export function PersonLink({id}:{id:string}){const{state}=useArena();const p=[...(state?.users??[]),...samplePeople].find(p=>p.id===id);return <a href={`/profile/${encodeURIComponent(id)}`} className="person-link"><UserAvatar person={p}/>{p?.username??'Contender'}{id.startsWith('demo-')&&<span className="micro-tag">sample</span>}</a>}
export function DebateCard({d}:{d:Debate}){const{state,act,busy}=useArena();const[reply,setReply]=useState(false);const[body,setBody]=useState('');const likes=state?.likes.filter(l=>l.debate===d.id)??[];const liked=likes.some(l=>l.user===state?.me.id);const replies=state?.debates.filter(r=>r.parent===d.id)??[];return <article className={`debate-card ${d.parent?'reply-card':''}`}><PersonLink id={d.user}/><p>{d.body}</p><div className="debate-actions"><button disabled={busy||d.user===state?.me.id} className={liked?'liked':''} onClick={()=>act({action:'like',debate:d.id},liked?'Upvote removed':'Argument upvoted')}><ArrowUp size={16}/>{likes.length} useful</button>{!d.parent&&<button onClick={()=>setReply(!reply)}><MessageSquare size={15}/>{replies.length} replies</button>}<small>{d.created?new Date(d.created).toLocaleDateString():'Sample argument'}</small></div>{reply&&<><form className="reply-form" onSubmit={async e=>{e.preventDefault();if(await act({action:'debate',matchup:d.matchup,parent:d.id,body},'Reply posted')){setBody('');setReply(false);}}}><label className="sr-only" htmlFor={`reply-${d.id}`}>Your reply</label><textarea id={`reply-${d.id}`} placeholder="Add a thoughtful reply…" minLength={10} maxLength={1200} required value={body} onChange={e=>setBody(e.target.value)}/><button className="button primary" disabled={busy}>Post reply</button></form>{replies.map(r=><DebateCard key={r.id} d={r}/>)}</>}</article>}
export function OrderList({ids,setIds}:{ids:string[];setIds:(ids:string[])=>void}){function move(i:number,d:number){const next=[...ids];[next[i],next[i+d]]=[next[i+d],next[i]];setIds(next);}return <div className="order-list">{ids.map((id,i)=>{const c=competitor(id);return <div key={id}><span className="rank-number">{i+1}</span><Portrait c={c}/><strong>{c.name}</strong><Score c={c}/><button type="button" aria-label={`Move ${c.name} up`} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={17}/></button><button type="button" aria-label={`Move ${c.name} down`} disabled={i===ids.length-1} onClick={()=>move(i,1)}><ArrowDown size={17}/></button><button type="button" aria-label={'Remove '+c.name+' from ranking'} disabled={ids.length<=2} onClick={()=>setIds(ids.filter(x=>x!==id))}><X size={16}/></button></div>;})}</div>}
