import {database} from '../../../db/store';
import {getAccountUser} from '../../../lib/account-auth';
import {fantasyCards} from '../../../lib/fantasy-store';
import {moments,validateMomentPlays} from '../../../lib/moments';
import {z} from 'zod';
export const dynamic='force-dynamic';
const headers={'Cache-Control':'no-store'};
export async function GET(){try{const account=await getAccountUser(),db=database();const events=await fantasyCards(db);if(!account)return Response.json({balance:null,owned:[],plays:[],events},{headers});const [wallet,owned,plays]=await Promise.all([db.prepare('SELECT balance FROM coin_wallets WHERE user=?').bind(account.userId).first<{balance:number}>(),db.prepare('SELECT card FROM moment_purchases WHERE user=?').bind(account.userId).all<{card:string}>(),db.prepare('SELECT * FROM moment_plays WHERE user=? ORDER BY created DESC,event,slot').bind(account.userId).all()]);return Response.json({balance:wallet?.balance??0,owned:owned.results.map(r=>r.card),plays:plays.results,events},{headers});}catch{return Response.json({error:'Could not load Moments. Please retry.'},{status:503,headers});}}
const input=z.discriminatedUnion('action',[z.object({action:z.literal('buy'),card:z.string().max(40)}).strict(),z.object({action:z.literal('lineup'),event:z.string().max(80),cards:z.array(z.string().max(40)).max(3)}).strict()]);
export async function POST(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid request origin.'},{status:403});try{const account=await getAccountUser();if(!account)return Response.json({error:'Sign in to collect and play Moments.'},{status:401});const body=await req.text();if(body.length>1024)return Response.json({error:'Request too large.'},{status:413});const parsed=input.safeParse(JSON.parse(body));if(!parsed.success)return Response.json({error:'Choose a Moment or a valid lineup.'},{status:400});const db=database(),id=account.userId,p=parsed.data;
 if(p.action==='buy'){const card=moments.find(m=>m.id===p.card);if(!card)return Response.json({error:'Moment not found.'},{status:404});if(await db.prepare('SELECT card FROM moment_purchases WHERE user=? AND card=?').bind(id,card.id).first())return Response.json({ok:true,alreadyOwned:true});try{await db.prepare('INSERT INTO moment_purchases(user,card,price,created) VALUES(?,?,?,?)').bind(id,card.id,card.price,Date.now()).run();}catch{if(!await db.prepare('SELECT card FROM moment_purchases WHERE user=? AND card=?').bind(id,card.id).first())return Response.json({error:'Not enough Arena Coins. Refresh your balance and try again.'},{status:400});}return Response.json({ok:true});}
 const events=await fantasyCards(db),event=events.find(e=>e.id===p.event);if(!event)return Response.json({error:'Event not found.'},{status:404});const owned=await db.prepare('SELECT card FROM moment_purchases WHERE user=?').bind(id).all<{card:string}>();const now=Date.now(),error=validateMomentPlays(event,p.cards,owned.results.map(r=>r.card),now);if(error)return Response.json({error},{status:400});
 // D1 batches are atomic. Trigger checks use the stored event and clock as a final lock guard.
 await db.batch([db.prepare('DELETE FROM moment_plays WHERE user=? AND event=?').bind(id,event.id),...p.cards.map((cardId,slot)=>{const card=moments.find(m=>m.id===cardId)!;const bout=event.bouts.find(b=>b.outcome==='pending'&&(b.red.id===card.fighter||b.blue.id===card.fighter))!;return db.prepare('INSERT INTO moment_plays(user,event,slot,card,fighter,bout,red,blue,created) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,event.id,slot,cardId,card.fighter,bout.id,bout.red.id,bout.blue.id,now);})]);return Response.json({ok:true});
 }catch{return Response.json({error:'This lineup could not be saved. The event may have started; refresh and try again.'},{status:400});}}
