import {getAccountUser,passwordHash,equalHash,randomToken,digest} from '../../../lib/account-auth';
import {accountCookie,requestToken,recoveryCode,recoveryDigest,securityLimit,rotateCredentials,type Credentials} from '../../../lib/account-security';
import {database} from '../../../db/store';
import {z} from 'zod';
export const dynamic='force-dynamic';const headers={'Cache-Control':'no-store'};
export async function GET(){try{const account=await getAccountUser();if(!account)return Response.json({error:'Sign in to manage your account.'},{status:401,headers});const db=database();const [security,preferences,sessions]=await Promise.all([db.prepare('SELECT recovery_hash IS NOT NULL AS hasRecovery,recovery_created AS recoveryCreated FROM auth_accounts WHERE id=?').bind(account.userId).first(),db.prepare('SELECT compact,reduce_motion AS reduceMotion,hide_predictions AS hidePredictions FROM user_settings WHERE user=?').bind(account.userId).first(),db.prepare('SELECT COUNT(*) AS activeSessions FROM auth_sessions s JOIN auth_accounts a ON a.id=s.user WHERE s.user=? AND s.expires>? AND s.version=a.password_version').bind(account.userId,Date.now()).first()]);return Response.json({...security,...sessions,preferences:preferences??{compact:0,reduceMotion:0,hidePredictions:0}},{headers});}catch{return Response.json({error:'Could not load settings.'},{status:503,headers});}}
const input=z.discriminatedUnion('action',[
 z.object({action:z.literal('preferences'),compact:z.boolean(),reduceMotion:z.boolean(),hidePredictions:z.boolean()}),
 z.object({action:z.literal('password'),currentPassword:z.string().min(1).max(128),newPassword:z.string().min(12).max(128)}),
 z.object({action:z.literal('recovery'),currentPassword:z.string().max(128).optional()}),
 z.object({action:z.literal('signoutOthers')})
]);
export async function POST(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid request origin.'},{status:403});try{const user=await getAccountUser();if(!user)return Response.json({error:'Sign in to manage your account.'},{status:401});const body=await req.text();if(body.length>2048)return Response.json({error:'Request too large.'},{status:413});const parsed=input.safeParse(JSON.parse(body));if(!parsed.success)return Response.json({error:parsed.error.issues[0].message},{status:400});const p=parsed.data,db=database();
 if(p.action==='preferences'){await db.prepare('INSERT INTO user_settings(user,compact,reduce_motion,hide_predictions) VALUES(?,?,?,?) ON CONFLICT(user) DO UPDATE SET compact=excluded.compact,reduce_motion=excluded.reduce_motion,hide_predictions=excluded.hide_predictions').bind(user.userId,+p.compact,+p.reduceMotion,+p.hidePredictions).run();return Response.json({ok:true});}
 if(p.action==='signoutOthers'){await db.prepare('DELETE FROM auth_sessions WHERE user=? AND token_hash!=?').bind(user.userId,await digest(requestToken(req))).run();return Response.json({ok:true});}
 if(!await securityLimit(db,req,user.userId))return Response.json({error:'Too many attempts. Try again in 15 minutes.'},{status:429,headers:{'Retry-After':'900'}});
 const account=await db.prepare('SELECT id,password_hash,salt,password_version,recovery_hash FROM auth_accounts WHERE id=?').bind(user.userId).first<Credentials>();if(!account)return Response.json({error:'Account unavailable.'},{status:401});
 const current=p.currentPassword??'';if(p.action==='password'||account.recovery_hash){if(!equalHash(await passwordHash(current,account.salt),account.password_hash))return Response.json({error:'Current password is incorrect.'},{status:401});}
 const code=recoveryCode(),codeHash=await recoveryDigest(code);
 if(p.action==='recovery'){const result=await db.prepare("UPDATE auth_accounts SET recovery_hash=?,recovery_created=? WHERE id=? AND password_version=? AND COALESCE(recovery_hash,'')=?").bind(codeHash,Date.now(),account.id,account.password_version,account.recovery_hash??'').run();if(!result.meta.changes)return Response.json({error:'Account security changed. Reload settings and try again.'},{status:409});return Response.json({ok:true,recoveryCode:code},{headers});}
 const salt=randomToken();const token=await rotateCredentials(db,account,await passwordHash(p.newPassword,salt),salt,codeHash);if(!token)return Response.json({error:'Account security changed. Try again.'},{status:409});return Response.json({ok:true,recoveryCode:code},{headers:{...headers,'Set-Cookie':accountCookie(req,token)}});
 }catch{return Response.json({error:'Could not update account settings.'},{status:400});}}
