import {database} from '../../../db/store';
import {getAccountUser} from '../../../lib/account-auth';
import {shopItems,styleDefaults} from '../../../lib/shop';
import {z} from 'zod';
export const dynamic='force-dynamic';
export async function GET(){try{const account=await getAccountUser();if(!account)return Response.json({balance:null,owned:[],equipped:styleDefaults});const db=database();const [wallet,owned,equipped]=await Promise.all([db.prepare('SELECT balance FROM coin_wallets WHERE user=?').bind(account.userId).first<{balance:number}>(),db.prepare('SELECT item FROM shop_purchases WHERE user=?').bind(account.userId).all<{item:string}>(),db.prepare('SELECT frame,banner,title FROM shop_equipped WHERE user=?').bind(account.userId).first()]);return Response.json({balance:wallet?.balance??0,owned:owned.results.map(i=>i.item),equipped:equipped??styleDefaults},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Could not load your collection.'},{status:503});}}
const input=z.discriminatedUnion('action',[z.object({action:z.literal('buy'),item:z.string().max(40)}),z.object({action:z.literal('equip'),item:z.string().max(40)}),z.object({action:z.literal('reset'),kind:z.enum(['frame','banner','title'])})]);
export async function POST(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid request origin.'},{status:403});try{const account=await getAccountUser();if(!account)return Response.json({error:'Sign in to collect your arena style.'},{status:401});const text=await req.text();if(text.length>512)return Response.json({error:'Request too large.'},{status:413});const parsed=input.safeParse(JSON.parse(text));if(!parsed.success)return Response.json({error:'Choose a shop item.'},{status:400});const p=parsed.data,db=database();
if(p.action==='reset'){await db.prepare(`INSERT INTO shop_equipped(user,${p.kind}) VALUES (?,?) ON CONFLICT(user) DO UPDATE SET ${p.kind}=excluded.${p.kind}`).bind(account.userId,styleDefaults[p.kind]).run();return Response.json({ok:true});}
const item=shopItems.find(i=>i.id===p.item);if(!item)return Response.json({error:'Item not found.'},{status:404});const owned=await db.prepare('SELECT item FROM shop_purchases WHERE user=? AND item=?').bind(account.userId,item.id).first();if(p.action==='buy'){if(owned)return Response.json({ok:true,alreadyOwned:true});const wallet=await db.prepare('SELECT balance FROM coin_wallets WHERE user=?').bind(account.userId).first<{balance:number}>();if(!wallet||wallet.balance<item.price)return Response.json({error:'Not enough Arena Coins for this item.'},{status:400});try{await db.prepare('INSERT INTO shop_purchases(user,item,price,created) VALUES (?,?,?,?)').bind(account.userId,item.id,item.price,Date.now()).run();}catch(e){if(!await db.prepare('SELECT item FROM shop_purchases WHERE user=? AND item=?').bind(account.userId,item.id).first())throw e;}return Response.json({ok:true});}
if(!owned)return Response.json({error:'Collect this item before equipping it.'},{status:403});await db.prepare(`INSERT INTO shop_equipped(user,${item.kind}) VALUES (?,?) ON CONFLICT(user) DO UPDATE SET ${item.kind}=excluded.${item.kind}`).bind(account.userId,item.value).run();return Response.json({ok:true});
}catch{return Response.json({error:'Could not save that change. Refresh your balance and try again.'},{status:400});}}
