export type LiveFighter={id:string;name:string;winner:boolean;record:string;stats:{label:string;value:string}[]};
export type LiveBout={id:string;division:string;state:string;status:string;round:number|null;clock:string;fighters:LiveFighter[]};
export type LiveEvent={id:string;name:string;date:string;state:string;status:string;source:string;bouts:LiveBout[]};
export type NewsItem={title:string;source:string;date:string};
export const fightStatKeys=[['knockDowns','Knockdowns'],['sigStrikesLanded','Significant strikes landed'],['sigStrikesAttempted','Significant strikes attempted'],['totalStrikesLanded','Total strikes landed'],['totalStrikesAttempted','Total strikes attempted'],['takedownsLanded','Takedowns landed'],['takedownsAttempted','Takedowns attempted'],['submissions','Submissions (ESPN)'],['timeInControl','Control time']] as const;
export function parseFightStats(input:any){const categories=input?.splits?.categories;if(!Array.isArray(categories))throw Error('Stats are not available yet.');const all=categories.flatMap((c:any)=>Array.isArray(c.stats)?c.stats:[]);return {rows:fightStatKeys.map(([key,label])=>{const found=all.find((s:any)=>s.name===key);return{label,value:found?.displayValue!=null?String(found.displayValue).slice(0,40):null};}),sourceUpdatedAt:all.find((s:any)=>s.name==='wallclock')?.displayValue??null};}
export function safeESPN(value:unknown){try{const u=new URL(String(value));return u.protocol==='https:'&&(u.hostname==='espn.com'||u.hostname.endsWith('.espn.com'))?u.href:'';}catch{return '';}}
export function parseScoreboard(input:unknown):LiveEvent[]{const data=input as {events?:any[]};if(!Array.isArray(data?.events))throw Error('Unexpected event feed.');return data.events.slice(0,6).filter(e=>/^\d+$/.test(e.id)&&Array.isArray(e.competitions)).map(e=>({id:e.id,name:String(e.name).slice(0,160),date:String(e.date),state:e.status?.type?.state??'pre',status:String(e.status?.type?.description??'Scheduled'),source:safeESPN(e.links?.find((l:any)=>l.rel?.includes('summary'))?.href)||'https://www.espn.com/mma/',bouts:e.competitions.slice(0,30).filter((b:any)=>Array.isArray(b.competitors)&&b.competitors.length===2).map((b:any)=>({id:String(b.id),division:String(b.type?.abbreviation??''),state:b.status?.type?.state??'pre',status:String(b.status?.type?.shortDetail??b.status?.type?.description??'Scheduled'),round:Number.isInteger(b.status?.period)?b.status.period:null,clock:String(b.status?.displayClock??''),fighters:b.competitors.map((f:any)=>({id:String(f.id),name:String(f.athlete?.displayName??f.athlete?.fullName??'Fighter'),winner:f.winner===true,record:String(f.records?.find((r:any)=>r.type==='total')?.summary??''),stats:(Array.isArray(f.statistics)?f.statistics:[]).slice(0,12).filter((s:any)=>s.displayValue!=null||s.value!=null).map((s:any)=>({label:String(s.label??s.displayName??s.name??'Statistic').slice(0,80),value:String(s.displayValue??s.value).slice(0,40)}))}))}))}));}
const decode=(text:string)=>text.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').trim();
export function parseNews(xml:string):NewsItem[]{if(!xml.includes('<rss'))throw Error('Unexpected news feed.');const tag=(x:string,name:string)=>decode(x.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]??'');return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].slice(0,8).map(m=>({title:tag(m[1],'title').slice(0,180),source:safeESPN(tag(m[1],'link')),date:tag(m[1],'pubDate')})).filter(n=>n.title&&n.source);}
export async function cachedFeed<T>(db:D1Database,key:string,url:string,ttl:number,parse:(data:any)=>T,json=true,origin?:string){const now=Date.now();await db.prepare("INSERT OR IGNORE INTO live_feed_cache(key,data) VALUES(?,'null')").bind(key).run();let row=await db.prepare('SELECT * FROM live_feed_cache WHERE key=?').bind(key).first<{data:string;checked:number;attempted:number;error:string}>();if(!row)throw Error('Feed cache unavailable.');if(now-Math.max(row.checked,row.attempted)>ttl){const claim=await db.prepare('UPDATE live_feed_cache SET attempted=? WHERE key=? AND attempted<?').bind(now,key,now-ttl).run();if(claim.meta.changes){try{const bridge=process.env.NODE_ENV==='development'&&origin&&['127.0.0.1','localhost'].includes(new URL(origin).hostname);const target=bridge?origin+'/__versus_public_feed?source='+encodeURIComponent(url):url;const r=await fetch(target,{signal:AbortSignal.timeout(7000),headers:{'User-Agent':'VERSUS-live-feed/1.0'}});if(!r.ok)throw Error('Source unavailable.');const text=await r.text();if(text.length>2_000_000)throw Error('Feed too large.');const data=parse(json?JSON.parse(text):text);await db.prepare("UPDATE live_feed_cache SET data=?,checked=?,error='' WHERE key=?").bind(JSON.stringify(data),now,key).run();}catch{await db.prepare('UPDATE live_feed_cache SET error=? WHERE key=?').bind('Source update unavailable. Showing the last fetched data, if any.',key).run();}}row=await db.prepare('SELECT * FROM live_feed_cache WHERE key=?').bind(key).first<typeof row>()??row;}
return{items:JSON.parse(row.data) as T|null,checkedAt:row.checked,error:row.error};}
