import type {FantasyEvent,FantasyBout} from './fantasy';
export type Moment={id:string;fighter:string;portrait:string;name:string;title:string;event:string;date:string;story:string;price:number;tier:'Iconic'|'Legendary';color:string;source:string};
const ufc300='https://www.ufc.com/news/main-card-results-highlights-winner-interviews-ufc-300-pereira-vs-hill';
const ufc275='https://www.ufc.com/news/ufc-275-teixeira-vs-prochazka-fight-results-highlights-winner-interviews-singapore';
export const moments:Moment[]=[
{id:'volkanovski-276',fighter:'alexander-volkanovski',portrait:'alexander-volkanovski',name:'Alexander Volkanovski',title:'NO DOUBT',event:'UFC 276',date:'July 2, 2022',story:'Volkanovski wins every round on all three scorecards to close his trilogy with Max Holloway.',price:150,tier:'Iconic',color:'#81b5f2',source:'https://www.ufc.com/news/ufc-276-adesanya-vs-cannonier-results'},
{id:'merab-306',fighter:'merab-dvalishvili',portrait:'merab-dvalishvili',name:'Merab Dvalishvili',title:'THE MACHINE',event:'UFC 306',date:'September 14, 2024',story:'Dvalishvili defeats Sean O’Malley by unanimous decision and leaves Sphere with the bantamweight belt.',price:150,tier:'Iconic',color:'#bfadff',source:'https://www.ufc.com/news/main-card-results-highlights-winner-interviews-ufc-306-omalley-vs-dvalishvili-noche-ufc-sphere'},
{id:'yan-251',fighter:'petr-yan',portrait:'petr-yan',name:'Petr Yan',title:'NO MERCY',event:'UFC 251',date:'July 2020',story:'Yan stops José Aldo in round five to capture the vacant bantamweight championship on Fight Island.',price:200,tier:'Iconic',color:'#f18c78',source:'https://www.ufc.com/news/ufc-251-results-usman-masvidal-yan-aldo-holloway-volkanovski-fight-island'},
{id:'volkov-overeem',fighter:'alexander-volkov',portrait:'alexander-volkov',name:'Alexander Volkov',title:'DRAGO UNLEASHED',event:'UFC Fight Night',date:'February 6, 2021',story:'Volkov stops Alistair Overeem with strikes in round two of their heavyweight main event.',price:100,tier:'Iconic',color:'#80d8c3',source:'https://www.ufc.com/news/ufc-fight-night-overeem-vs-volkov-results-winners-vegas-18'},
{id:'holloway-last-second',fighter:'max-holloway',portrait:'max-holloway',name:'Max Holloway',title:'THE FINAL SECOND',event:'UFC 300',date:'April 13, 2024',story:'Holloway stops Justin Gaethje at 4:59 of round five to claim the BMF belt.',price:450,tier:'Legendary',color:'#ea825c',source:ufc300},
{id:'pereira-300',fighter:'alex-pereira',portrait:'pereira',name:'Alex Pereira',title:'STONE COLD',event:'UFC 300',date:'April 13, 2024',story:'Pereira knocks out Jamahal Hill in the opening round of the landmark main event.',price:400,tier:'Legendary',color:'#c5f74f',source:ufc300},
{id:'topuria-298',fighter:'ilia-topuria',portrait:'topuria',name:'Ilia Topuria',title:'A NEW REIGN',event:'UFC 298',date:'February 17, 2024',story:'Topuria knocks out Alexander Volkanovski in round two to take the featherweight title.',price:350,tier:'Legendary',color:'#c696ff',source:'https://www.ufc.com/news/main-card-results-highlights-winner-interviews-ufc-298-volkanovski-vs-topuria'},
{id:'edwards-278',fighter:'leon-edwards',portrait:'leon-edwards',name:'Leon Edwards',title:'HEAD SHOT',event:'UFC 278',date:'August 20, 2022',story:'A fifth-round head kick against Kamaru Usman turns the welterweight title fight upside down.',price:350,tier:'Legendary',color:'#76bfff',source:'https://www.ufc.com/news/ufc-278-usman-vs-edwards-2-results-highlights-winner-interviews-salt-lake-city'},
{id:'adesanya-287',fighter:'israel-adesanya',portrait:'adesanya',name:'Israel Adesanya',title:'THE REDEMPTION',event:'UFC 287',date:'April 8, 2023',story:'Adesanya knocks out Alex Pereira in round two and reclaims the middleweight belt.',price:350,tier:'Legendary',color:'#74e0ce',source:'https://www.ufc.com/news/ufc-287-pereira-vs-adesanya-2-results-highlights-winner-interviews-miami'},
{id:'allen-muniz',fighter:'brendan-allen',portrait:'brendan-allen',name:'Brendan Allen',title:'ALL IN',event:'UFC Fight Night',date:'February 25, 2023',story:'Allen submits André Muniz in round three in an unexpected main event at the APEX.',price:100,tier:'Iconic',color:'#a3b7ff',source:'https://www.ufc.com/news/ufc-bonus-coverage-2023-performance-fight-of-the-night'},
{id:'jiri-275',fighter:'jiri-prochazka',portrait:'jiri-prochazka',name:'Jiří Procházka',title:'NEVER SAY DIE',event:'UFC 275',date:'June 2022',story:'Procházka submits Glover Teixeira late in round five to become light heavyweight champion.',price:300,tier:'Legendary',color:'#ff777d',source:ufc275},
{id:'zhang-275',fighter:'zhang-weili',portrait:'zhang-weili',name:'Zhang Weili',title:'SPIN TO WIN',event:'UFC 275',date:'June 2022',story:'A spinning backfist ends Zhang’s rematch with Joanna Jędrzejczyk in round two.',price:250,tier:'Iconic',color:'#f0be72',source:ufc275},
{id:'pereira-281',fighter:'alex-pereira',portrait:'pereira',name:'Alex Pereira',title:'THE FIFTH ROUND',event:'UFC 281',date:'November 12, 2022',story:'Pereira stops Israel Adesanya in round five to capture the middleweight championship.',price:300,tier:'Iconic',color:'#deae72',source:'https://www.ufc.com/news/ufc-281-adesanya-vs-pereira-esparza-vs-zhang-results-winner-interviews'},
{id:'zhang-300',fighter:'zhang-weili',portrait:'zhang-weili',name:'Zhang Weili',title:'HISTORY MADE',event:'UFC 300',date:'April 13, 2024',story:'Zhang defeats Yan Xiaonan by unanimous decision in the first all-Chinese UFC title fight.',price:200,tier:'Iconic',color:'#f092c3',source:ufc300}
,{"id":"archive-conor-mcgregor-194","fighter":"conor-mcgregor","portrait":"conor-mcgregor","name":"Conor McGregor","title":"THIRTEEN SECONDS","event":"UFC 194","date":"December 12, 2015","story":"McGregor knocks out José Aldo just 13 seconds into their featherweight title fight.","price":450,"tier":"Legendary","color":"#c5f74f","source":"https://www.ufc.com/news/ufc-194-aldo-vs-mcgregor-final-results"},
{"id":"archive-luke-rockhold-194","fighter":"luke-rockhold","portrait":"ruku-rotsukuhoruto","name":"Luke Rockhold","title":"A NEW CHAPTER","event":"UFC 194","date":"December 12, 2015","story":"Rockhold stops Chris Weidman to claim the middleweight championship.","price":250,"tier":"Iconic","color":"#81b5f2","source":"https://www.ufc.com/news/ufc-194-aldo-vs-mcgregor-final-results"},
{"id":"archive-khabib-nurmagomedov-229","fighter":"khabib-nurmagomedov","portrait":"khabib","name":"Khabib Nurmagomedov","title":"UNDEFEATED","event":"UFC 229","date":"October 6, 2018","story":"Nurmagomedov submits Conor McGregor to retain the lightweight championship.","price":400,"tier":"Legendary","color":"#f0be72","source":"https://www.ufc.com/event/ufc-229"},
{"id":"archive-tony-ferguson-229","fighter":"tony-ferguson","portrait":"tony-ferguson","name":"Tony Ferguson","title":"EL CUCUY RETURNS","event":"UFC 229","date":"October 6, 2018","story":"Ferguson defeats Anthony Pettis by a stoppage between rounds in their wild co-main event.","price":200,"tier":"Iconic","color":"#bfadff","source":"https://www.ufc.com/event/ufc-229"},
{"id":"archive-georges-st-pierre-217","fighter":"georges-st-pierre","portrait":"gsp","name":"Georges St-Pierre","title":"THE RETURN","event":"UFC 217","date":"November 4, 2017","story":"St-Pierre returns from a long layoff and submits Michael Bisping to become middleweight champion.","price":400,"tier":"Legendary","color":"#80d8c3","source":"https://www.ufc.com/news/ufc-217-bisping-vs-st-pierre-final-results"},
{"id":"archive-rose-namajunas-217","fighter":"rose-namajunas","portrait":"rose-namajunas","name":"Rose Namajunas","title":"BELIEVE IT","event":"UFC 217","date":"November 4, 2017","story":"Namajunas stops Joanna Jędrzejczyk to win the strawweight championship.","price":300,"tier":"Legendary","color":"#f092c3","source":"https://www.ufc.com/news/ufc-217-bisping-vs-st-pierre-final-results"},
{"id":"archive-kamaru-usman-261","fighter":"kamaru-usman","portrait":"kamaru-usman","name":"Kamaru Usman","title":"NIGHTMARE POWER","event":"UFC 261","date":"April 24, 2021","story":"Usman knocks out Jorge Masvidal in their welterweight title rematch.","price":350,"tier":"Legendary","color":"#c5f74f","source":"https://www.ufc.com/news/ufc-261-usman-vs-masvidal-2-zhang-namajunas-results-highlights-interviews-winners"},
{"id":"archive-rose-namajunas-261","fighter":"rose-namajunas","portrait":"rose-namajunas","name":"Rose Namajunas","title":"THUG ROSE","event":"UFC 261","date":"April 24, 2021","story":"Namajunas finishes Zhang Weili with a head kick to reclaim the strawweight title.","price":350,"tier":"Legendary","color":"#81b5f2","source":"https://www.ufc.com/news/ufc-261-usman-vs-masvidal-2-zhang-namajunas-results-highlights-interviews-winners"},
{"id":"archive-valentina-shevchenko-261","fighter":"valentina-shevchenko","portrait":"valentina-shevchenko","name":"Valentina Shevchenko","title":"BULLETPROOF","event":"UFC 261","date":"April 24, 2021","story":"Shevchenko stops Jessica Andrade to retain her flyweight championship.","price":250,"tier":"Iconic","color":"#f0be72","source":"https://www.ufc.com/news/ufc-261-usman-vs-masvidal-2-zhang-namajunas-results-highlights-interviews-winners"},
{"id":"archive-nate-diaz-196","fighter":"nate-diaz","portrait":"nate-diaz","name":"Nate Diaz","title":"STOCKTON SHOCK","event":"UFC 196","date":"March 5, 2016","story":"Diaz submits Conor McGregor in a welterweight main event.","price":400,"tier":"Legendary","color":"#bfadff","source":"https://www.ufc.com/news/ufc-196-results-and-news"},
{"id":"archive-miesha-tate-196","fighter":"miesha-tate","portrait":"miesha-tate","name":"Miesha Tate","title":"NEVER OUT","event":"UFC 196","date":"March 5, 2016","story":"Tate submits Holly Holm in the final round to win the bantamweight title.","price":300,"tier":"Legendary","color":"#80d8c3","source":"https://www.ufc.com/news/ufc-196-results-and-news"},
{"id":"archive-amanda-nunes-200","fighter":"amanda-nunes","portrait":"amanda-nunes","name":"Amanda Nunes","title":"THE LIONESS RISES","event":"UFC 200","date":"July 9, 2016","story":"Nunes submits Miesha Tate to become bantamweight champion.","price":350,"tier":"Legendary","color":"#f092c3","source":"https://www.ufc.com/news/ufc-200-results-and-news-vegas"},
{"id":"archive-jose-aldo-200","fighter":"jose-aldo","portrait":"jose-aldo","name":"José Aldo","title":"BACK ON TOP","event":"UFC 200","date":"July 9, 2016","story":"Aldo defeats Frankie Edgar by unanimous decision to claim the interim featherweight title.","price":250,"tier":"Iconic","color":"#c5f74f","source":"https://www.ufc.com/news/ufc-200-results-and-news-vegas"},
{"id":"archive-cain-velasquez-200","fighter":"cain-velasquez","portrait":"cain-velasquez","name":"Cain Velasquez","title":"HEAVY PRESSURE","event":"UFC 200","date":"July 9, 2016","story":"Velasquez finishes Travis Browne in the opening round.","price":200,"tier":"Iconic","color":"#81b5f2","source":"https://www.ufc.com/news/ufc-200-results-and-news-vegas"},
{"id":"archive-conor-mcgregor-205","fighter":"conor-mcgregor","portrait":"conor-mcgregor","name":"Conor McGregor","title":"TWO BELTS","event":"UFC 205","date":"November 12, 2016","story":"McGregor stops Eddie Alvarez and becomes a simultaneous UFC champion in two divisions.","price":450,"tier":"Legendary","color":"#f0be72","source":"https://www.ufc.com/node/80862"},
{"id":"archive-joanna-jedrzejczyk-205","fighter":"joanna-jedrzejczyk","portrait":"joanna-jedrzejczyk","name":"Joanna Jędrzejczyk","title":"THE CHAMPION’S STANDARD","event":"UFC 205","date":"November 12, 2016","story":"Jędrzejczyk defeats Karolina Kowalkiewicz by unanimous decision to retain her strawweight belt.","price":200,"tier":"Iconic","color":"#bfadff","source":"https://www.ufc.com/node/80862"},
{"id":"archive-brock-lesnar-100","fighter":"brock-lesnar","portrait":"brock-lesnar","name":"Brock Lesnar","title":"THE REMATCH","event":"UFC 100","date":"July 11, 2009","story":"Lesnar stops Frank Mir to unify the heavyweight championship.","price":350,"tier":"Legendary","color":"#80d8c3","source":"https://www.ufc.com.br/news/relembrando-ufc-100-redencao-lesnar-nocaute-hendo-georges-st-pierre-jon-jones"},
{"id":"archive-georges-st-pierre-100","fighter":"georges-st-pierre","portrait":"gsp","name":"Georges St-Pierre","title":"FIVE ROUND MASTERCLASS","event":"UFC 100","date":"July 11, 2009","story":"St-Pierre defeats Thiago Alves by unanimous decision to retain the welterweight title.","price":300,"tier":"Legendary","color":"#f092c3","source":"https://www.ufc.com.br/news/relembrando-ufc-100-redencao-lesnar-nocaute-hendo-georges-st-pierre-jon-jones"},
{"id":"archive-dan-henderson-100","fighter":"dan-henderson","portrait":"dan-henderson","name":"Dan Henderson","title":"THE H-BOMB","event":"UFC 100","date":"July 11, 2009","story":"Henderson knocks out Michael Bisping in their middleweight bout.","price":350,"tier":"Legendary","color":"#c5f74f","source":"https://www.ufc.com.br/news/relembrando-ufc-100-redencao-lesnar-nocaute-hendo-georges-st-pierre-jon-jones"},
{"id":"archive-jiri-prochazka-300","fighter":"jiri-prochazka","portrait":"jiri-prochazka","name":"Jiří Procházka","title":"BACK IN THE FIRE","event":"UFC 300","date":"April 13, 2024","story":"Procházka stops Aleksandar Rakić in the second round.","price":250,"tier":"Iconic","color":"#81b5f2","source":"https://www.ufc.com.br/news/ufc-300-pereira-hill-resultados-card-completo"},
{"id":"archive-kayla-harrison-300","fighter":"kayla-harrison","portrait":"kayla-harrison","name":"Kayla Harrison","title":"WELCOME TO THE OCTAGON","event":"UFC 300","date":"April 13, 2024","story":"Harrison submits Holly Holm in her UFC debut.","price":250,"tier":"Iconic","color":"#f0be72","source":"https://www.ufc.com.br/news/ufc-300-pereira-hill-resultados-card-completo"},
{"id":"archive-deiveson-figueiredo-300","fighter":"deiveson-figueiredo","portrait":"deiveson-figueiredo","name":"Deiveson Figueiredo","title":"GOD OF WAR","event":"UFC 300","date":"April 13, 2024","story":"Figueiredo submits Cody Garbrandt in their bantamweight bout.","price":200,"tier":"Iconic","color":"#bfadff","source":"https://www.ufc.com.br/news/ufc-300-pereira-hill-resultados-card-completo"},
{"id":"archive-bo-nickal-300","fighter":"bo-nickal","portrait":"bo-nickal","name":"Bo Nickal","title":"THE NEXT STEP","event":"UFC 300","date":"April 13, 2024","story":"Nickal submits Cody Brundage on the landmark UFC 300 main card.","price":150,"tier":"Iconic","color":"#80d8c3","source":"https://www.ufc.com.br/news/ufc-300-pereira-hill-resultados-card-completo"},
{"id":"series2-jorge-masvidal-239","fighter":"jorge-masvidal","portrait":"jorge-masvidal","name":"Jorge Masvidal","title":"FIVE SECONDS","event":"UFC 239","date":"July 6, 2019","story":"Jorge Masvidal defeats Ben Askren by KO/TKO in round 1 at UFC 239.","price":350,"tier":"Legendary","color":"#fbb075","source":"http://www.ufcstats.com/fight-details/70af72a72b31fe4d"},
{"id":"series2-amanda-nunes-239","fighter":"amanda-nunes","portrait":"amanda-nunes","name":"Amanda Nunes","title":"HIGH KICK HISTORY","event":"UFC 239","date":"July 6, 2019","story":"Amanda Nunes defeats Holly Holm by KO/TKO in round 1 at UFC 239.","price":350,"tier":"Legendary","color":"#a4cfff","source":"http://www.ufcstats.com/fight-details/69c06be4f87ccdab"},
{"id":"series2-jones-239","fighter":"jon-jones","portrait":"jones","name":"Jon Jones","title":"A CHAMPION’S TEST","event":"UFC 239","date":"July 6, 2019","story":"Jon Jones defeats Thiago Santos by split decision at UFC 239.","price":200,"tier":"Iconic","color":"#d3a8ff","source":"http://www.ufcstats.com/fight-details/8fcdfee81cc604e3"},
{"id":"series2-holly-holm-193","fighter":"holly-holm","portrait":"holly-holm","name":"Holly Holm","title":"THE UPSET","event":"UFC 193","date":"November 14, 2015","story":"Holly Holm defeats Ronda Rousey by KO/TKO in round 2 at UFC 193.","price":350,"tier":"Legendary","color":"#9de2c0","source":"http://www.ufcstats.com/fight-details/08af25ef4252b138"},
{"id":"series2-joanna-jedrzejczyk-193","fighter":"joanna-jedrzejczyk","portrait":"joanna-jedrzejczyk","name":"Joanna Jędrzejczyk","title":"CHAMPION IN MELBOURNE","event":"UFC 193","date":"November 14, 2015","story":"Joanna Jędrzejczyk defeats Valerie Letourneau by unanimous decision at UFC 193.","price":200,"tier":"Iconic","color":"#f4a5c6","source":"http://www.ufcstats.com/fight-details/391d458db6dae33b"},
{"id":"series2-michael-chandler-274","fighter":"michael-chandler","portrait":"michael-chandler","name":"Michael Chandler","title":"LIGHTS OUT","event":"UFC 274","date":"May 7, 2022","story":"Michael Chandler defeats Tony Ferguson by KO/TKO in round 2 at UFC 274.","price":350,"tier":"Legendary","color":"#d6f56b","source":"http://www.ufcstats.com/fight-details/a2ebb5f86eb64f22"},
{"id":"series2-charles-oliveira-274","fighter":"charles-oliveira","portrait":"charles-oliveira","name":"Charles Oliveira","title":"DO BRONXS DELIVERS","event":"UFC 274","date":"May 7, 2022","story":"Charles Oliveira defeats Justin Gaethje by submission in round 1 at UFC 274.","price":350,"tier":"Legendary","color":"#fbb075","source":"http://www.ufcstats.com/fight-details/7d4e49d8a6678157"},
{"id":"series2-carla-esparza-274","fighter":"carla-esparza","portrait":"carla-esparza","name":"Carla Esparza","title":"BACK TO THE BELT","event":"UFC 274","date":"May 7, 2022","story":"Carla Esparza defeats Rose Namajunas by split decision at UFC 274.","price":200,"tier":"Iconic","color":"#a4cfff","source":"http://www.ufcstats.com/fight-details/9d61012a6020516e"},
{"id":"series2-michael-bisping-199","fighter":"michael-bisping","portrait":"michael-bisping","name":"Michael Bisping","title":"THE COUNT’S NIGHT","event":"UFC 199","date":"June 4, 2016","story":"Michael Bisping defeats Luke Rockhold by KO/TKO in round 1 at UFC 199.","price":350,"tier":"Legendary","color":"#d3a8ff","source":"http://www.ufcstats.com/fight-details/812ff38f0ed409ca"},
{"id":"series2-dominick-cruz-199","fighter":"dominick-cruz","portrait":"dominick-cruz","name":"Dominick Cruz","title":"THE DOMINATOR","event":"UFC 199","date":"June 4, 2016","story":"Dominick Cruz defeats Urijah Faber by unanimous decision at UFC 199.","price":200,"tier":"Iconic","color":"#9de2c0","source":"http://www.ufcstats.com/fight-details/9c884cbc3791bf60"},
{"id":"series2-max-holloway-199","fighter":"max-holloway","portrait":"max-holloway","name":"Max Holloway","title":"BLESSED IN CALIFORNIA","event":"UFC 199","date":"June 4, 2016","story":"Max Holloway defeats Ricardo Lamas by unanimous decision at UFC 199.","price":200,"tier":"Iconic","color":"#f4a5c6","source":"http://www.ufcstats.com/fight-details/345b1bc51f0f5e86"},
{"id":"series2-dan-henderson-199","fighter":"dan-henderson","portrait":"dan-henderson","name":"Dan Henderson","title":"ONE MORE H-BOMB","event":"UFC 199","date":"June 4, 2016","story":"Dan Henderson defeats Hector Lombard by KO/TKO in round 2 at UFC 199.","price":350,"tier":"Legendary","color":"#d6f56b","source":"http://www.ufcstats.com/fight-details/c33cc8b85b9a202c"},
{"id":"series2-dustin-poirier-199","fighter":"dustin-poirier","portrait":"dustin-poirier","name":"Dustin Poirier","title":"DIAMOND PRESSURE","event":"UFC 199","date":"June 4, 2016","story":"Dustin Poirier defeats King Green by KO/TKO in round 1 at UFC 199.","price":350,"tier":"Legendary","color":"#fbb075","source":"http://www.ufcstats.com/fight-details/e86a77b69d50a834"},
{"id":"series2-brian-ortega-199","fighter":"brian-ortega","portrait":"brian-ortega","name":"Brian Ortega","title":"T-CITY RISING","event":"UFC 199","date":"June 4, 2016","story":"Brian Ortega defeats Clay Guida by KO/TKO in round 3 at UFC 199.","price":350,"tier":"Legendary","color":"#a4cfff","source":"http://www.ufcstats.com/fight-details/db1be0ca226d3a2f"},
{"id":"series2-beneil-dariush-199","fighter":"beneil-dariush","portrait":"beneil-dariush","name":"Beneil Dariush","title":"BREAKTHROUGH","event":"UFC 199","date":"June 4, 2016","story":"Beneil Dariush defeats James Vick by KO/TKO in round 1 at UFC 199.","price":350,"tier":"Legendary","color":"#d3a8ff","source":"http://www.ufcstats.com/fight-details/2c65d5d20cc893e4"},
{"id":"series2-amanda-nunes-232","fighter":"amanda-nunes","portrait":"amanda-nunes","name":"Amanda Nunes","title":"DOUBLE CHAMP","event":"UFC 232","date":"December 29, 2018","story":"Amanda Nunes defeats Cristiane Justino by KO/TKO in round 1 at UFC 232.","price":350,"tier":"Legendary","color":"#9de2c0","source":"http://www.ufcstats.com/fight-details/3278e45b30f7dd33"},
{"id":"series2-jones-232","fighter":"jon-jones","portrait":"jones","name":"Jon Jones","title":"RETURN TO THE THRONE","event":"UFC 232","date":"December 29, 2018","story":"Jon Jones defeats Alexander Gustafsson by KO/TKO in round 3 at UFC 232.","price":350,"tier":"Legendary","color":"#f4a5c6","source":"http://www.ufcstats.com/fight-details/ceaae1db8ccde29c"},
{"id":"series2-chris-weidman-162","fighter":"chris-weidman","portrait":"chris-weidman","name":"Chris Weidman","title":"THE REIGN ENDS","event":"UFC 162","date":"July 6, 2013","story":"Chris Weidman defeats Anderson Silva by KO/TKO in round 2 at UFC 162.","price":350,"tier":"Legendary","color":"#d6f56b","source":"http://www.ufcstats.com/fight-details/9a6a6716cdfadc98"},
{"id":"series2-frankie-edgar-162","fighter":"frankie-edgar","portrait":"frankie-edgar","name":"Frankie Edgar","title":"THE ANSWER","event":"UFC 162","date":"July 6, 2013","story":"Frankie Edgar defeats Charles Oliveira by unanimous decision at UFC 162.","price":200,"tier":"Iconic","color":"#fbb075","source":"http://www.ufcstats.com/fight-details/6453b20a65c62cfe"},
{"id":"series2-cub-swanson-162","fighter":"cub-swanson","portrait":"cub-swanson","name":"Cub Swanson","title":"KILLER CUB","event":"UFC 162","date":"July 6, 2013","story":"Cub Swanson defeats Dennis Siver by KO/TKO in round 3 at UFC 162.","price":350,"tier":"Legendary","color":"#a4cfff","source":"http://www.ufcstats.com/fight-details/c3601529b7a7d489"},
{"id":"series2-robbie-lawler-189","fighter":"robbie-lawler","portrait":"robbie-lawler","name":"Robbie Lawler","title":"THE FIFTH ROUND WAR","event":"UFC 189","date":"July 11, 2015","story":"Robbie Lawler defeats Rory MacDonald by KO/TKO in round 5 at UFC 189.","price":350,"tier":"Legendary","color":"#d3a8ff","source":"http://www.ufcstats.com/fight-details/ecb4534c0066c5f3"},
{"id":"series2-conor-mcgregor-189","fighter":"conor-mcgregor","portrait":"conor-mcgregor","name":"Conor McGregor","title":"THE INTERIM KING","event":"UFC 189","date":"July 11, 2015","story":"Conor McGregor defeats Chad Mendes by KO/TKO in round 2 at UFC 189.","price":350,"tier":"Legendary","color":"#9de2c0","source":"http://www.ufcstats.com/fight-details/70290140b6a8e038"},
{"id":"series2-zhang-weili-281","fighter":"zhang-weili","portrait":"zhang-weili","name":"Zhang Weili","title":"RECLAIMED","event":"UFC 281","date":"November 12, 2022","story":"Zhang Weili defeats Carla Esparza by submission in round 2 at UFC 281.","price":350,"tier":"Legendary","color":"#f4a5c6","source":"http://www.ufcstats.com/fight-details/85b5d59f8eea976a"},
{"id":"series2-dustin-poirier-281","fighter":"dustin-poirier","portrait":"dustin-poirier","name":"Dustin Poirier","title":"DIAMOND AT THE GARDEN","event":"UFC 281","date":"November 12, 2022","story":"Dustin Poirier defeats Michael Chandler by submission in round 3 at UFC 281.","price":350,"tier":"Legendary","color":"#d6f56b","source":"http://www.ufcstats.com/fight-details/4bf3010fdeea9d93"},
{"id":"series2-silva-126","fighter":"anderson-silva","portrait":"silva","name":"Anderson Silva","title":"THE SPIDER’S KICK","event":"UFC 126","date":"February 5, 2011","story":"Anderson Silva defeats Vitor Belfort by KO/TKO in round 1 at UFC 126.","price":350,"tier":"Legendary","color":"#fbb075","source":"http://www.ufcstats.com/fight-details/87c73e2086214b5c"},
{"id":"series2-ronta-raushi-157","fighter":"ronta-raushi","portrait":"ronta-raushi","name":"Ronda Rousey","title":"THE FIRST DEFENSE","event":"UFC 157","date":"February 23, 2013","story":"Ronda Rousey defeats Liz Carmouche by submission in round 1 at UFC 157.","price":350,"tier":"Legendary","color":"#a4cfff","source":"http://www.ufcstats.com/fight-details/e9e6023dbba9a8b0"},
{"id":"series2-max-holloway-206","fighter":"max-holloway","portrait":"max-holloway","name":"Max Holloway","title":"BLESSED ERA BEGINS","event":"UFC 206","date":"December 10, 2016","story":"Max Holloway defeats Anthony Pettis by KO/TKO in round 3 at UFC 206.","price":350,"tier":"Legendary","color":"#d3a8ff","source":"http://www.ufcstats.com/fight-details/977a758d869f9e7a"},
{"id":"series2-robbie-lawler-195","fighter":"robbie-lawler","portrait":"robbie-lawler","name":"Robbie Lawler","title":"RUTHLESS RESOLVE","event":"UFC 195","date":"January 2, 2016","story":"Robbie Lawler defeats Carlos Condit by split decision at UFC 195.","price":200,"tier":"Iconic","color":"#9de2c0","source":"http://www.ufcstats.com/fight-details/f079cb2db8dbbf04"},
{"id":"series2-zhang-weili-248","fighter":"zhang-weili","portrait":"zhang-weili","name":"Zhang Weili","title":"FIVE ROUNDS OF HISTORY","event":"UFC 248","date":"March 7, 2020","story":"Zhang Weili defeats Joanna Jedrzejczyk by split decision at UFC 248.","price":200,"tier":"Iconic","color":"#f4a5c6","source":"http://www.ufcstats.com/fight-details/cf0a6466b762c668"},
{"id":"series2-justin-gaethje-291","fighter":"justin-gaethje","portrait":"justin-gaethje","name":"Justin Gaethje","title":"SALT LAKE HEAD KICK","event":"UFC 291","date":"July 29, 2023","story":"Justin Gaethje defeats Dustin Poirier by KO/TKO in round 2 at UFC 291.","price":350,"tier":"Legendary","color":"#d6f56b","source":"http://www.ufcstats.com/fight-details/c27e33ee8ef53866"}
];
export type MomentPlay={user:string;event:string;slot:number;card:string;fighter:string;bout:string;red:string;blue:string;state:'pending'|'settled';payout:number;result:string;created:number;settled:number|null};
export const momentRules={slots:3,win:40,finish:25,roundOne:15};
export function momentBonus(bout:FantasyBout,fighter:string){if(bout.outcome==='pending')return null;if(bout.outcome!=='finished'||bout.winner!==fighter)return{payout:0,result:bout.outcome==='finished'?'Loss':bout.outcome==='nc'?'No contest':bout.outcome==='draw'?'Draw':'Cancelled / replaced'};const finish=/submission|\bTKO\b|\bKO\b/i.test(bout.method);const payout=40+(finish?25:0)+(finish&&bout.round===1?15:0);return{payout,result:`Win${finish?' + finish':''}${finish&&bout.round===1?' + round one':''}`};}
export function validateMomentPlays(event:FantasyEvent,cards:string[],owned:string[],now=Date.now()):string|null{
 if(event.replay||now>=event.startsAt)return'This event is locked. Choose an upcoming official card.';
 if(cards.length>3||new Set(cards).size!==cards.length)return'Play up to three different Moments.';
 const fighters=new Set<string>(),bouts=new Set<string>();
 for(const id of cards){const card=moments.find(m=>m.id===id);if(!card||!owned.includes(id))return'Collect each Moment before playing it.';const bout=event.bouts.find(b=>b.outcome==='pending'&&(b.red.id===card.fighter||b.blue.id===card.fighter));if(!bout)return'That fighter is not available on this event.';if(fighters.has(card.fighter)||bouts.has(bout.id))return'Choose different fighters from different bouts.';fighters.add(card.fighter);bouts.add(bout.id);}
 return null;
}
