import type {FantasyEvent,FantasyBout} from './fantasy';
export type Moment={id:string;fighter:string;portrait:string;name:string;title:string;event:string;date:string;story:string;price:number;tier:'Iconic'|'Legendary';color:string;source:string};
const ufc300='https://www.ufc.com/news/main-card-results-highlights-winner-interviews-ufc-300-pereira-vs-hill';
const ufc275='https://www.ufc.com/news/ufc-275-teixeira-vs-prochazka-fight-results-highlights-winner-interviews-singapore';
export const moments:Moment[]=[
{id:'volkanovski-276',fighter:'alexander-volkanovski',portrait:'alexander-volkanovski',name:'Alexander Volkanovski',title:'NO DOUBT',event:'UFC 276',date:'July 2, 2022',story:'Volkanovski wins every round on all three scorecards to close his trilogy with Max Holloway.',price:150,tier:'Iconic',color:'#81b5f2',source:'https://www.ufc.com/news/ufc-276-adesanya-vs-cannonier-results'},
{id:'merab-306',fighter:'merab-dvalishvili',portrait:'merab-dvalishvili',name:'Merab Dvalishvili',title:'THE MACHINE',event:'UFC 306',date:'September 14, 2024',story:'Dvalishvili defeats Sean O’Malley by unanimous decision and leaves Sphere with the bantamweight belt.',price:150,tier:'Iconic',color:'#bfadff',source:'https://www.ufc.com/news/main-card-results-highlights-winner-interviews-ufc-306-omalley-vs-dvalishvili-noche-ufc-sphere'},
{id:'yan-251',fighter:'petr-yan',portrait:'petr-yan',name:'Petr Yan',title:'NO MERCY',event:'UFC 251',date:'July 2020',story:'Yan stops José Aldo in round five to capture the vacant bantamweight championship on Fight Island.',price:200,tier:'Iconic',color:'#f18c78',source:'https://www.ufc.com/news/ufc-251-results-usman-masvidal-yan-aldo-holloway-volkanovski-fight-island'},
{id:'volkov-overeem',fighter:'alexander-volkov',portrait:'alexander-volkov',name:'Alexander Volkov',title:'DRAGO UNLEASHED',event:'UFC Fight Night',date:'February 6, 2021',story:'Volkov stops Alistair Overeem with strikes in round two of their heavyweight main event.',price:100,tier:'Iconic',color:'#80d8c3',source:'https://www.ufc.com/news/ufc-fight-night-overeem-vs-volkov-results-winners-vegas-18'},
{id:'holloway-last-second',fighter:'max-holloway',portrait:'max-holloway',name:'Max Holloway',title:'THE FINAL SECOND',event:'UFC 300',date:'April 13, 2024',story:'Holloway stops Justin Gaethje at 4:59 of round five to claim the BMF belt.',price:450,tier:'Legendary',color:'#ea825c',source:ufc300},
{id:'pereira-300',fighter:'alex-pereira',portrait:'pereira',name:'Alex Pereira',title:'STONE COLD',event:'UFC 300',date:'April 13, 2024',story:'Pereira knocks out Jamahal Hill in the opening round of the landmark main event.',price:400,tier:'Legendary',color:'#c5f74f',source:ufc300},
{id:'topuria-298',fighter:'ilia-topuria',portrait:'topuria',name:'Ilia Topuria',title:'A NEW REIGN',event:'UFC 298',date:'February 17, 2024',story:'Topuria knocks out Alexander Volkanovski in round two to take the featherweight title.',price:350,tier:'Legendary',color:'#c696ff',source:'https://www.ufc.com/news/main-card-results-highlights-winner-interviews-ufc-298-volkanovski-vs-topuria'},
{id:'edwards-278',fighter:'leon-edwards',portrait:'leon-edwards',name:'Leon Edwards',title:'HEAD SHOT',event:'UFC 278',date:'August 20, 2022',story:'A fifth-round head kick against Kamaru Usman turns the welterweight title fight upside down.',price:350,tier:'Legendary',color:'#76bfff',source:'https://www.ufc.com/news/ufc-278-usman-vs-edwards-2-results-highlights-winner-interviews-salt-lake-city'},
{id:'adesanya-287',fighter:'israel-adesanya',portrait:'adesanya',name:'Israel Adesanya',title:'THE REDEMPTION',event:'UFC 287',date:'April 8, 2023',story:'Adesanya knocks out Alex Pereira in round two and reclaims the middleweight belt.',price:350,tier:'Legendary',color:'#74e0ce',source:'https://www.ufc.com/news/ufc-287-pereira-vs-adesanya-2-results-highlights-winner-interviews-miami'},
{id:'allen-muniz',fighter:'brendan-allen',portrait:'brendan-allen',name:'Brendan Allen',title:'ALL IN',event:'UFC Fight Night',date:'February 25, 2023',story:'Allen submits André Muniz in round three in an unexpected main event at the APEX.',price:100,tier:'Iconic',color:'#a3b7ff',source:'https://www.ufc.com/news/ufc-bonus-coverage-2023-performance-fight-of-the-night'},
{id:'jiri-275',fighter:'jiri-prochazka',portrait:'jiri-prochazka',name:'Jiří Procházka',title:'NEVER SAY DIE',event:'UFC 275',date:'June 2022',story:'Procházka submits Glover Teixeira late in round five to become light heavyweight champion.',price:300,tier:'Legendary',color:'#ff777d',source:ufc275},
{id:'zhang-275',fighter:'zhang-weili',portrait:'zhang-weili',name:'Zhang Weili',title:'SPIN TO WIN',event:'UFC 275',date:'June 2022',story:'A spinning backfist ends Zhang’s rematch with Joanna Jędrzejczyk in round two.',price:250,tier:'Iconic',color:'#f0be72',source:ufc275},
{id:'pereira-281',fighter:'alex-pereira',portrait:'pereira',name:'Alex Pereira',title:'THE FIFTH ROUND',event:'UFC 281',date:'November 12, 2022',story:'Pereira stops Israel Adesanya in round five to capture the middleweight championship.',price:300,tier:'Iconic',color:'#deae72',source:'https://www.ufc.com/news/ufc-281-adesanya-vs-pereira-esparza-vs-zhang-results-winner-interviews'},
{id:'zhang-300',fighter:'zhang-weili',portrait:'zhang-weili',name:'Zhang Weili',title:'HISTORY MADE',event:'UFC 300',date:'April 13, 2024',story:'Zhang defeats Yan Xiaonan by unanimous decision in the first all-Chinese UFC title fight.',price:200,tier:'Iconic',color:'#f092c3',source:ufc300}
];
export type MomentPlay={user:string;event:string;slot:number;card:string;fighter:string;bout:string;red:string;blue:string;state:'pending'|'settled';payout:number;result:string;created:number;settled:number|null};
export const momentRules={slots:3,win:40,finish:25,roundOne:15};
export function momentBonus(bout:FantasyBout,fighter:string){if(bout.outcome==='pending')return null;if(bout.outcome!=='finished'||bout.winner!==fighter)return{payout:0,result:bout.outcome==='finished'?'Loss':bout.outcome==='nc'?'No contest':bout.outcome==='draw'?'Draw':'Cancelled / replaced'};const finish=/submission|\bTKO\b|\bKO\b/i.test(bout.method);const payout=40+(finish?25:0)+(finish&&bout.round===1?15:0);return{payout,result:`Win${finish?' + finish':''}${finish&&bout.round===1?' + round one':''}`};}
export function validateMomentPlays(event:FantasyEvent,cards:string[],owned:string[],now=Date.now()):string|null{
 if(event.replay||now>=event.startsAt)return'This event is locked. Choose an upcoming official card.';
 if(cards.length>3||new Set(cards).size!==cards.length)return'Play up to three different Moments.';
 const fighters=new Set<string>(),bouts=new Set<string>();
 for(const id of cards){const card=moments.find(m=>m.id===id);if(!card||!owned.includes(id))return'Collect each Moment before playing it.';const bout=event.bouts.find(b=>b.outcome==='pending'&&(b.red.id===card.fighter||b.blue.id===card.fighter));if(!bout)return'That fighter is not available on this event.';if(fighters.has(card.fighter)||bouts.has(bout.id))return'Choose different fighters from different bouts.';fighters.add(card.fighter);bouts.add(bout.id);}
 return null;
}
