import type {FantasyEvent,FantasyBout} from './fantasy';
export type Moment={id:string;fighter:string;portrait:string;name:string;title:string;event:string;date:string;story:string;price:number;tier:'Iconic'|'Legendary';color:string;source:string};
const ufc300='https://www.ufc.com/news/main-card-results-highlights-winner-interviews-ufc-300-pereira-vs-hill';
const ufc275='https://www.ufc.com/news/ufc-275-teixeira-vs-prochazka-fight-results-highlights-winner-interviews-singapore';
export const moments:Moment[]=[
{id:'volkanovski-276',fighter:'alexander-volkanovski',portrait:'alexander-volkanovski',name:'Alexander Volkanovski',title:'NO DOUBT',event:'UFC 276',date:'July 2, 2022',story:'Volkanovski wins every round on all three scorecards to close his trilogy with Max Holloway.',price:150,tier:'Iconic',color:'#81b5f2',source:'https://www.ufc.com/news/ufc-276-adesanya-vs-cannonier-results'},
{id:'merab-306',fighter:'merab-dvalishvili',portrait:'merab-dvalishvili',name:'Merab Dvalishvili',title:'THE MACHINE',event:'UFC 306',date:'September 14, 2024',story:'Dvalishvili defeats Sean O’Malley by unanimous decision and leaves Sphere with the bantamweight belt.',price:150,tier:'Iconic',color:'#bfadff',source:'https://www.ufc.com/news/main-card-results-highlights-winner-interviews-ufc-306-omalley-vs-dvalishvili-noche-ufc-sphere'},
{id:'yan-251',fighter:'petr-yan',portrait:'petr-yan',name:'Petr Yan',title:'NO MERCY',event:'UFC 251',date:'July 2020',story:'Yan stops José Aldo in round five to capture the vacant bantamweight championship on Fight Island.',price:200,tier:'Iconic',color:'#f18c78',source:'https://www.ufc.com/news/ufc-251-results-usman-masvidal-yan-aldo-holloway-volkanovski-fight-island'},
{id:'volkov-overeem',fighter:'alexander-volkov',portrait:'alexander-volkov',name:'Alexander Volkov',title:'DRAGO UNLEASHED',event:'UFC Fight Night',date:'February 6, 2021',story:'Volkov stops Alistair Overeem with strikes in round two of their heavyweight main event.',price:100,tier:'Iconic',color:'#80d8c3',source:'https://www.ufc.com/news/ufc-fight-night-overeem-vs-volkov-results-winners-vegas-18'},
{id:'holloway-last-second',fighter:'max-holloway',portrait:'max-holloway',name:'Max Holloway',title:'THE FINAL SECOND',event:'UFC 300',date:'April 13, 2024',story:'Holloway stops Justin Gaethje at 4:59 of round five to claim the BMF belt.',price:450,tier:'Legendary',color:'#ea825c',source:ufc300},
{id:'pereira-300',fighter:'alex-pereira',portrait:'pereira',name:'Alex Pereira',title:'STONE COLD',event:'UFC 300',date:'April 13, 2024',story:'Pereira knocks out Jamahal Hill in the opening round of the landmark main event.',price:400,tier:'Legendary',color:'#c5f74f',source:ufc300},
{id:'topuria-298',fighter:'ilia-topuria',portrait:'topuria',name:'Ilia Topuria',title:'A NEW REIGN',event:'UFC 298',date:'February 17, 2024',story:'Topuria knocks out Alexander Volkanovski in round two to take the featherweight title.',price:350,tier:'Legendary',color:'#c696ff',source:'https://www.ufc.com/news/main-card-results-highlights-winner-interviews-ufc-298-volkanovski-vs-topuria'},
{id:'edwards-278',fighter:'leon-edwards',portrait:'leon-edwards',name:'Leon Edwards',title:'HEAD SHOT',event:'UFC 278',date:'August 20, 2022',story:'A fifth-round head kick against Kamaru Usman turns the welterweight title fight upside down.',price:350,tier:'Legendary',color:'#76bfff',source:'https://www.ufc.com/news/ufc-278-usman-vs-edwards-2-results-highlights-winner-interviews-salt-lake-city'},
{id:'adesanya-287',fighter:'israel-adesanya',portrait:'adesanya',name:'Israel Adesanya',title:'THE REDEMPTION',event:'UFC 287',date:'April 8, 2023',story:'Adesanya knocks out Alex Pereira in round two and reclaims the middleweight belt.',price:350,tier:'Legendary',color:'#74e0ce',source:'https://www.ufc.com/news/ufc-287-pereira-vs-adesanya-2-results-highlights-winner-interviews-miami'},
{id:'allen-muniz',fighter:'brendan-allen',portrait:'brendan-allen',name:'Brendan Allen',title:'ALL IN',event:'UFC Fight Night',date:'February 25, 2023',story:'Allen submits André Muniz in round three in an unexpected main event at the APEX.',price:100,tier:'Iconic',color:'#a3b7ff',source:'https://www.ufc.com/news/ufc-bonus-coverage-2023-performance-fight-of-the-night'},
{id:'jiri-275',fighter:'jiri-prochazka',portrait:'jiri-prochazka',name:'Jiří Procházka',title:'NEVER SAY DIE',event:'UFC 275',date:'June 2022',story:'Procházka submits Glover Teixeira late in round five to become light heavyweight champion.',price:300,tier:'Legendary',color:'#ff777d',source:ufc275},
{id:'zhang-275',fighter:'zhang-weili',portrait:'zhang-weili',name:'Zhang Weili',title:'SPIN TO WIN',event:'UFC 275',date:'June 2022',story:'A spinning backfist ends Zhang’s rematch with Joanna Jędrzejczyk in round two.',price:250,tier:'Iconic',color:'#f0be72',source:ufc275},
{id:'pereira-281',fighter:'alex-pereira',portrait:'pereira',name:'Alex Pereira',title:'THE FIFTH ROUND',event:'UFC 281',date:'November 12, 2022',story:'Pereira stops Israel Adesanya in round five to capture the middleweight championship.',price:300,tier:'Iconic',color:'#deae72',source:'https://www.ufc.com/news/ufc-281-adesanya-vs-pereira-esparza-vs-zhang-results-winner-interviews'},
{id:'zhang-300',fighter:'zhang-weili',portrait:'zhang-weili',name:'Zhang Weili',title:'HISTORY MADE',event:'UFC 300',date:'April 13, 2024',story:'Zhang defeats Yan Xiaonan by unanimous decision in the first all-Chinese UFC title fight.',price:200,tier:'Iconic',color:'#f092c3',source:ufc300}
,{"id":"archive-conor-mcgregor-194","fighter":"conor-mcgregor","portrait":"conor-mcgregor","name":"Conor McGregor","title":"THIRTEEN SECONDS","event":"UFC 194","date":"December 12, 2015","story":"McGregor knocks out José Aldo just 13 seconds into their featherweight title fight.","price":450,"tier":"Legendary","color":"#c5f74f","source":"https://www.ufc.com/news/ufc-194-aldo-vs-mcgregor-final-results"},
{"id":"archive-luke-rockhold-194","fighter":"luke-rockhold","portrait":"ruku-rotsukuhoruto","name":"Luke Rockhold","title":"A NEW CHAPTER","event":"UFC 194","date":"December 12, 2015","story":"Rockhold stops Chris Weidman to claim the middleweight championship.","price":250,"tier":"Iconic","color":"#81b5f2","source":"https://www.ufc.com/news/ufc-194-aldo-vs-mcgregor-final-results"},
{"id":"archive-khabib-nurmagomedov-229","fighter":"khabib-nurmagomedov","portrait":"khabib","name":"Khabib Nurmagomedov","title":"UNDEFEATED","event":"UFC 229","date":"October 6, 2018","story":"Nurmagomedov submits Conor McGregor to retain the lightweight championship.","price":400,"tier":"Legendary","color":"#f0be72","source":"https://www.ufc.com/event/ufc-229"},
{"id":"archive-tony-ferguson-229","fighter":"tony-ferguson","portrait":"tony-ferguson","name":"Tony Ferguson","title":"EL CUCUY RETURNS","event":"UFC 229","date":"October 6, 2018","story":"Ferguson defeats Anthony Pettis by a stoppage between rounds in their wild co-main event.","price":200,"tier":"Iconic","color":"#bfadff","source":"https://www.ufc.com/event/ufc-229"},
{"id":"archive-georges-st-pierre-217","fighter":"georges-st-pierre","portrait":"gsp","name":"Georges St-Pierre","title":"THE RETURN","event":"UFC 217","date":"November 4, 2017","story":"St-Pierre returns from a long layoff and submits Michael Bisping to become middleweight champion.","price":400,"tier":"Legendary","color":"#80d8c3","source":"https://www.ufc.com/news/ufc-217-bisping-vs-st-pierre-final-results"},
{"id":"archive-rose-namajunas-217","fighter":"rose-namajunas","portrait":"rose-namajunas","name":"Rose Namajunas","title":"BELIEVE IT","event":"UFC 217","date":"November 4, 2017","story":"Namajunas stops Joanna Jędrzejczyk to win the strawweight championship.","price":300,"tier":"Legendary","color":"#f092c3","source":"https://www.ufc.com/news/ufc-217-bisping-vs-st-pierre-final-results"},
{"id":"archive-kamaru-usman-261","fighter":"kamaru-usman","portrait":"kamaru-usman","name":"Kamaru Usman","title":"NIGHTMARE POWER","event":"UFC 261","date":"April 24, 2021","story":"Usman knocks out Jorge Masvidal in their welterweight title rematch.","price":350,"tier":"Legendary","color":"#c5f74f","source":"https://www.ufc.com/news/ufc-261-usman-vs-masvidal-2-zhang-namajunas-results-highlights-interviews-winners"},
{"id":"archive-rose-namajunas-261","fighter":"rose-namajunas","portrait":"rose-namajunas","name":"Rose Namajunas","title":"THUG ROSE","event":"UFC 261","date":"April 24, 2021","story":"Namajunas finishes Zhang Weili with a head kick to reclaim the strawweight title.","price":350,"tier":"Legendary","color":"#81b5f2","source":"https://www.ufc.com/news/ufc-261-usman-vs-masvidal-2-zhang-namajunas-results-highlights-interviews-winners"},
{"id":"archive-valentina-shevchenko-261","fighter":"valentina-shevchenko","portrait":"valentina-shevchenko","name":"Valentina Shevchenko","title":"BULLETPROOF","event":"UFC 261","date":"April 24, 2021","story":"Shevchenko stops Jessica Andrade to retain her flyweight championship.","price":250,"tier":"Iconic","color":"#f0be72","source":"https://www.ufc.com/news/ufc-261-usman-vs-masvidal-2-zhang-namajunas-results-highlights-interviews-winners"},
{"id":"archive-nate-diaz-196","fighter":"nate-diaz","portrait":"nate-diaz","name":"Nate Diaz","title":"STOCKTON SHOCK","event":"UFC 196","date":"March 5, 2016","story":"Diaz submits Conor McGregor in a welterweight main event.","price":400,"tier":"Legendary","color":"#bfadff","source":"https://www.ufc.com/news/ufc-196-results-and-news"},
{"id":"archive-miesha-tate-196","fighter":"miesha-tate","portrait":"miesha-tate","name":"Miesha Tate","title":"NEVER OUT","event":"UFC 196","date":"March 5, 2016","story":"Tate submits Holly Holm in the final round to win the bantamweight title.","price":300,"tier":"Legendary","color":"#80d8c3","source":"https://www.ufc.com/news/ufc-196-results-and-news"},
{"id":"archive-amanda-nunes-200","fighter":"amanda-nunes","portrait":"amanda-nunes","name":"Amanda Nunes","title":"THE LIONESS RISES","event":"UFC 200","date":"July 9, 2016","story":"Nunes submits Miesha Tate to become bantamweight champion.","price":350,"tier":"Legendary","color":"#f092c3","source":"https://www.ufc.com/news/ufc-200-results-and-news-vegas"},
{"id":"archive-jose-aldo-200","fighter":"jose-aldo","portrait":"jose-aldo","name":"José Aldo","title":"BACK ON TOP","event":"UFC 200","date":"July 9, 2016","story":"Aldo defeats Frankie Edgar by unanimous decision to claim the interim featherweight title.","price":250,"tier":"Iconic","color":"#c5f74f","source":"https://www.ufc.com/news/ufc-200-results-and-news-vegas"},
{"id":"archive-cain-velasquez-200","fighter":"cain-velasquez","portrait":"cain-velasquez","name":"Cain Velasquez","title":"HEAVY PRESSURE","event":"UFC 200","date":"July 9, 2016","story":"Velasquez finishes Travis Browne in the opening round.","price":200,"tier":"Iconic","color":"#81b5f2","source":"https://www.ufc.com/news/ufc-200-results-and-news-vegas"},
{"id":"archive-conor-mcgregor-205","fighter":"conor-mcgregor","portrait":"conor-mcgregor","name":"Conor McGregor","title":"TWO BELTS","event":"UFC 205","date":"November 12, 2016","story":"McGregor stops Eddie Alvarez and becomes a simultaneous UFC champion in two divisions.","price":450,"tier":"Legendary","color":"#f0be72","source":"https://www.ufc.com/node/80862"},
{"id":"archive-joanna-jedrzejczyk-205","fighter":"joanna-jedrzejczyk","portrait":"joanna-jedrzejczyk","name":"Joanna Jędrzejczyk","title":"THE CHAMPION’S STANDARD","event":"UFC 205","date":"November 12, 2016","story":"Jędrzejczyk defeats Karolina Kowalkiewicz by unanimous decision to retain her strawweight belt.","price":200,"tier":"Iconic","color":"#bfadff","source":"https://www.ufc.com/node/80862"},
{"id":"archive-brock-lesnar-100","fighter":"brock-lesnar","portrait":"brock-lesnar","name":"Brock Lesnar","title":"THE REMATCH","event":"UFC 100","date":"July 11, 2009","story":"Lesnar stops Frank Mir to unify the heavyweight championship.","price":350,"tier":"Legendary","color":"#80d8c3","source":"https://www.ufc.com.br/news/relembrando-ufc-100-redencao-lesnar-nocaute-hendo-georges-st-pierre-jon-jones"},
{"id":"archive-georges-st-pierre-100","fighter":"georges-st-pierre","portrait":"gsp","name":"Georges St-Pierre","title":"FIVE ROUND MASTERCLASS","event":"UFC 100","date":"July 11, 2009","story":"St-Pierre defeats Thiago Alves by unanimous decision to retain the welterweight title.","price":300,"tier":"Legendary","color":"#f092c3","source":"https://www.ufc.com.br/news/relembrando-ufc-100-redencao-lesnar-nocaute-hendo-georges-st-pierre-jon-jones"},
{"id":"archive-dan-henderson-100","fighter":"dan-henderson","portrait":"dan-henderson","name":"Dan Henderson","title":"THE H-BOMB","event":"UFC 100","date":"July 11, 2009","story":"Henderson knocks out Michael Bisping in their middleweight bout.","price":350,"tier":"Legendary","color":"#c5f74f","source":"https://www.ufc.com.br/news/relembrando-ufc-100-redencao-lesnar-nocaute-hendo-georges-st-pierre-jon-jones"},
{"id":"archive-jiri-prochazka-300","fighter":"jiri-prochazka","portrait":"jiri-prochazka","name":"Jiří Procházka","title":"BACK IN THE FIRE","event":"UFC 300","date":"April 13, 2024","story":"Procházka stops Aleksandar Rakić in the second round.","price":250,"tier":"Iconic","color":"#81b5f2","source":"https://www.ufc.com.br/news/ufc-300-pereira-hill-resultados-card-completo"},
{"id":"archive-kayla-harrison-300","fighter":"kayla-harrison","portrait":"kayla-harrison","name":"Kayla Harrison","title":"WELCOME TO THE OCTAGON","event":"UFC 300","date":"April 13, 2024","story":"Harrison submits Holly Holm in her UFC debut.","price":250,"tier":"Iconic","color":"#f0be72","source":"https://www.ufc.com.br/news/ufc-300-pereira-hill-resultados-card-completo"},
{"id":"archive-deiveson-figueiredo-300","fighter":"deiveson-figueiredo","portrait":"deiveson-figueiredo","name":"Deiveson Figueiredo","title":"GOD OF WAR","event":"UFC 300","date":"April 13, 2024","story":"Figueiredo submits Cody Garbrandt in their bantamweight bout.","price":200,"tier":"Iconic","color":"#bfadff","source":"https://www.ufc.com.br/news/ufc-300-pereira-hill-resultados-card-completo"},
{"id":"archive-bo-nickal-300","fighter":"bo-nickal","portrait":"bo-nickal","name":"Bo Nickal","title":"THE NEXT STEP","event":"UFC 300","date":"April 13, 2024","story":"Nickal submits Cody Brundage on the landmark UFC 300 main card.","price":150,"tier":"Iconic","color":"#80d8c3","source":"https://www.ufc.com.br/news/ufc-300-pereira-hill-resultados-card-completo"}
];
export type MomentPlay={user:string;event:string;slot:number;card:string;fighter:string;bout:string;red:string;blue:string;state:'pending'|'settled';payout:number;result:string;created:number;settled:number|null};
export const momentRules={slots:3,win:40,finish:25,roundOne:15};
export function momentBonus(bout:FantasyBout,fighter:string){if(bout.outcome==='pending')return null;if(bout.outcome!=='finished'||bout.winner!==fighter)return{payout:0,result:bout.outcome==='finished'?'Loss':bout.outcome==='nc'?'No contest':bout.outcome==='draw'?'Draw':'Cancelled / replaced'};const finish=/submission|\bTKO\b|\bKO\b/i.test(bout.method);const payout=40+(finish?25:0)+(finish&&bout.round===1?15:0);return{payout,result:`Win${finish?' + finish':''}${finish&&bout.round===1?' + round one':''}`};}
export function validateMomentPlays(event:FantasyEvent,cards:string[],owned:string[],now=Date.now()):string|null{
 if(event.replay||now>=event.startsAt)return'This event is locked. Choose an upcoming official card.';
 if(cards.length>3||new Set(cards).size!==cards.length)return'Play up to three different Moments.';
 const fighters=new Set<string>(),bouts=new Set<string>();
 for(const id of cards){const card=moments.find(m=>m.id===id);if(!card||!owned.includes(id))return'Collect each Moment before playing it.';const bout=event.bouts.find(b=>b.outcome==='pending'&&(b.red.id===card.fighter||b.blue.id===card.fighter));if(!bout)return'That fighter is not available on this event.';if(fighters.has(card.fighter)||bouts.has(bout.id))return'Choose different fighters from different bouts.';fighters.add(card.fighter);bouts.add(bout.id);}
 return null;
}
