import {database} from '../../../db/store';
import {getAccountUser} from '../../../lib/account-auth';
import {ownerIdentity} from '../../../lib/owner';
import {fantasyCards} from '../../../lib/fantasy-store';
import {z} from 'zod';
export const dynamic='force-dynamic';
const headers={'Cache-Control':'no-store'};
export async function GET(req:Request){try{const event=new URL(req.url).searchParams.get('event');if(!event||event.length>80)return Response.json({error:'Choose an event.'},{status:400});const me=await getAccountUser();const r=await database().prepare(`SELECT c.id,c.user,c.event,c.body,c.created,u.username FROM event_comments c JOIN users u ON u.id=c.user WHERE c.event=? AND c.hidden=0 AND NOT EXISTS(SELECT 1 FROM account_blocks b WHERE (b.user=? AND b.target=c.user) OR (b.user=c.user AND b.target=?)) ORDER BY c.created DESC,c.id DESC LIMIT 100`).bind(event,me?.userId??'',me?.userId??'').all();return Response.json({items:r.results,signedIn:!!me},{headers});}catch{return Response.json({error:'Comments could not load.'},{status:503,headers});}}
const input=z.discriminatedUnion('action',[z.object({action:z.literal('post'),event:z.string().min(1).max(80),body:z.string().trim().min(10).max(1200)}).strict(),z.object({action:z.literal('hide'),id:z.string().uuid()}).strict()]);
export async function POST(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid request origin.'},{status:403});try{const me=await getAccountUser();if(!me)return Response.json({error:'Sign in to comment.'},{status:401});const raw=await req.text();if(raw.length>6000)return Response.json({error:'Comment too large.'},{status:413});const parsed=input.safeParse(JSON.parse(raw));if(!parsed.success)return Response.json({error:'Write a comment between 10 and 1,200 characters.'},{status:400});const db=database(),p=parsed.data;
if(p.action==='hide'){const row=await db.prepare('SELECT user FROM event_comments WHERE id=?').bind(p.id).first<{user:string}>();if(!row)return Response.json({error:'Comment not found.'},{status:404});if(row.user!==me.userId&&!await ownerIdentity())return Response.json({error:'You can only remove your own comments.'},{status:403});await db.prepare('UPDATE event_comments SET hidden=1 WHERE id=?').bind(p.id).run();}
else{const events=await fantasyCards(db,false);if(!events.some(e=>e.id===p.event))return Response.json({error:'Unknown tracked event.'},{status:400});const now=Date.now();const r=await db.prepare(`INSERT INTO event_comments(id,user,event,body,created) SELECT ?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM event_comments WHERE user=? AND created>?) AND (SELECT COUNT(*) FROM event_comments WHERE user=? AND created>?)<20 AND NOT EXISTS(SELECT 1 FROM event_comments WHERE user=? AND lower(trim(body))=lower(trim(?)) AND created>?)`).bind(crypto.randomUUID(),me.userId,p.event,p.body,now,me.userId,now-15000,me.userId,now-86400000,me.userId,p.body,now-86400000).run();if(!r.meta.changes)return Response.json({error:'Wait 15 seconds between comments. Daily limit: 20. Duplicate comments cannot be reposted today.'},{status:429});}
return Response.json({ok:true},{headers});}catch{return Response.json({error:'Could not save your comment.'},{status:400,headers});}}
