// Disposable accounts on the local preview; no real user wallet is changed.
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {writeFileSync,unlinkSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=new URL('../',import.meta.url),base='http://127.0.0.1:5173',ids=[],prefix='RewardsQA_'+randomBytes(3).toString('hex');let ip=0;
function sql(text){const file=new URL('qol-qa.sql',root);writeFileSync(file,text);try{const r=spawnSync(process.execPath,['--import','./scripts/sites-env.mjs','node_modules/wrangler/bin/wrangler.js','d1','execute','DB','--local','--config','wrangler.cloudflare.json','--file',fileURLToPath(file)],{cwd:root,encoding:'utf8'});if(r.status!==0)throw Error(r.stdout+r.stderr);}finally{unlinkSync(file);}}
async function req(path,body,cookie,origin=base){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{Origin:origin,'CF-Connecting-IP':`198.51.100.${++ip%250+1}`,...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});const raw=await r.text();let data;try{data=JSON.parse(raw);}catch{data={error:raw.slice(0,200)}}return{status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function register(n){const r=await req('/api/account',{action:'register',username:prefix+n,password:'QA-'+randomUUID()});assert.equal(r.status,200);const me=(await req('/api/arena',null,r.cookie)).data.me;ids.push(me.id);return{id:me.id,cookie:r.cookie};}
const balance=async account=>(await req('/api/coins',null,account.cookie)).data.wallet.balance;
try{const a=await register('_a'),b=await register('_b'),initial=await balance(a);assert.equal((await req('/api/rewards',{action:'daily'})).status,401);assert.equal((await req('/api/rewards',{action:'daily'},a.cookie,'https://evil.example')).status,403);assert.equal((await req('/api/rewards',{action:'comment',amount:999},a.cookie)).status,400);assert.equal((await req('/api/rewards',{action:'daily'},a.cookie)).data.claimed,true);assert.equal((await req('/api/rewards',{action:'daily'},a.cookie)).data.claimed,false);assert.equal(await balance(a),initial+40);
const events=(await req('/api/fantasy',null,a.cookie)).data.events,event=events.find(e=>!e.replay&&e.startsAt>Date.now());assert(event);
const comment={action:'post',event:event.id,body:'A thoughtful, respectful and useful analysis from a disposable QA account.'};assert.equal((await req('/api/event-comments',comment)).status,401);assert.equal((await req('/api/event-comments',comment,a.cookie,'https://evil.example')).status,403);assert.equal((await req('/api/event-comments',{...comment,event:'unknown'},a.cookie)).status,400);assert.equal((await req('/api/event-comments',comment,a.cookie)).status,200);assert.equal(await balance(a),initial+55);assert.equal((await req('/api/event-comments',comment,a.cookie)).status,429);
const list=(await req('/api/event-comments?event='+event.id,null,a.cookie)).data.items,row=list.find(c=>c.user===a.id);assert(row);assert.equal(row.body,comment.body);assert.equal((await req('/api/event-comments',{action:'hide',id:row.id},b.cookie)).status,403);assert.equal((await req('/api/event-comments',{action:'hide',id:row.id},a.cookie)).status,200);assert(!(await req('/api/event-comments?event='+event.id)).data.items.some(c=>c.id===row.id));
assert.equal((await req('/api/suggestions',{action:'create',title:'Reward progress test idea',body:'An original suggestion with sufficient detail to earn participation coins.',category:'Feature'},a.cookie)).status,200);assert.equal(await balance(a),initial+90);const idea=(await req('/api/suggestions')).data.items.find(c=>c.user===a.id);const b0=await balance(b);assert.equal((await req('/api/suggestions',{action:'vote',id:idea.id,enabled:true},b.cookie)).status,200);assert.equal(await balance(b),b0+5);await req('/api/suggestions',{action:'vote',id:idea.id,enabled:false},b.cookie);await req('/api/suggestions',{action:'vote',id:idea.id,enabled:true},b.cookie);assert.equal(await balance(b),b0+5);
const bout=event.bouts.find(b=>b.outcome==='pending');assert(bout);const pick={event:event.id,bout:bout.id,fighter:bout.red.id,amount:10};assert.equal((await req('/api/coins',pick,b.cookie)).status,200);assert.equal(await balance(b),b0+5-10+5);assert.equal((await req('/api/coins',pick,b.cookie)).status,409);
const team=event.bouts.filter(b=>b.outcome!=='cancelled').map(b=>b.red.cost<=b.blue.cost?b.red:b.blue).sort((x,y)=>x.cost-y.cost).slice(0,5);assert.equal(team.length,5);assert.ok(team.reduce((n,f)=>n+f.cost,0)<=60);const lineup={event:event.id,name:'Disposable QA team',fighters:team.map(f=>f.id),captain:team[0].id};assert.equal((await req('/api/fantasy',lineup,a.cookie)).status,200);assert.equal(await balance(a),initial+125);assert.equal((await req('/api/fantasy',{...lineup,name:'Renamed QA team'},a.cookie)).status,200);assert.equal(await balance(a),initial+125);
const profile={action:'profile',username:prefix+'_a',favorites:['mma'],bio:'An original account bio long enough for the reward.',favoriteFighter:'pereira'};assert.equal((await req('/api/arena',profile,a.cookie)).status,200);assert.equal(await balance(a),initial+170);assert.equal((await req('/api/arena',{...profile,favoriteFighter:'jones'},a.cookie)).status,200);assert.equal(await balance(a),initial+170);
assert.equal((await req('/api/arena',{action:'ranking',title:'Disposable QA rankings',category:'mma',competitors:['pereira','jones']},a.cookie)).status,200);assert.equal(await balance(a),initial+190);
const progress=(await req('/api/rewards',null,a.cookie)).data;assert.equal(progress.earned.find(e=>e.kind==='comment').count,1);assert.equal(progress.earned.find(e=>e.kind==='suggestion').count,1);assert.equal(progress.earned.find(e=>e.kind==='lineup').count,1);assert.equal(progress.earned.find(e=>e.kind==='ranking').count,1);assert.equal(progress.completed.length,2);assert.equal((await req('/api/live-stats?event=bad&bout=2')).status,400);assert.equal((await req('/api/live-stats?event=123&bout=456')).status,404);
const live=(await req('/api/live')).data;if(live.events?.items?.length){const e=live.events.items[0],s=await req('/api/live-stats?event='+e.id+'&bout='+e.bouts[0].id);assert.equal(s.status,200);assert.equal(s.data.fighters.length,2);assert.ok(s.data.fighters.some(f=>f.items?.rows.length));}
console.log('PASS: authenticated/idempotent daily claims, forged rewards rejected, comment origins and rate limits, author-only removals, automatic suggestion/support/pick rewards, vote replay protection, progress, validated live-bout IDs and real stats responses.');
}finally{if(ids.length)sql(ids.map(id=>`DELETE FROM rankings WHERE user='${id}';DELETE FROM fantasy_lineups WHERE user='${id}';DELETE FROM auth_accounts WHERE id='${id}';DELETE FROM users WHERE id='${id}';`).join(''));}
