import {getAccountUser,digest} from '../../../lib/account-auth';
import {database} from '../../../db/store';
import {z} from 'zod';
export const dynamic='force-dynamic';
const headers={'Cache-Control':'no-store'};
const personSelect='SELECT u.id,u.username,u.bio,u.location,u.avatar,u.accent,u.favoriteFighter,u.favorites,u.created,u.active,ph.updated AS photoUpdated,s.frame AS profileFrame,s.banner AS profileBanner,s.title AS profileTitle,CASE WHEN o.user IS NOT NULL OR p.approved=1 THEN 1 ELSE 0 END AS approved,CASE WHEN o.user IS NOT NULL THEN 1 ELSE 0 END AS owner,CASE WHEN r.number<=200 THEN 1 ELSE 0 END AS earlySupporter FROM users u JOIN auth_accounts a ON a.id=u.id LEFT JOIN profile_photos ph ON ph.user=u.id LEFT JOIN shop_equipped s ON s.user=u.id LEFT JOIN account_privileges p ON p.user=u.id LEFT JOIN owner_binding o ON o.user=u.id LEFT JOIN account_rewards r ON r.user=u.id ';
export async function GET(req:Request){try{const account=await getAccountUser();if(!account)return Response.json({error:'Sign in to find accounts and manage friends.'},{status:401,headers});const id=account.userId,db=database(),url=new URL(req.url);const q=(url.searchParams.get('q')??'').trim().slice(0,24);const offset=Math.min(5000,Math.max(0,Number.parseInt(url.searchParams.get('offset')??'0',10)||0));const pattern='%'+q.replace(/[\\%_]/g,'\\$&')+'%';const sort=url.searchParams.get('sort')==='newest'?'u.created DESC,u.id':'lower(u.username),u.id';
const [people,relationships,contacts,blocked]=await Promise.all([
db.prepare(personSelect+`WHERE u.id!=? AND u.username LIKE ? ESCAPE '\\' AND NOT EXISTS(SELECT 1 FROM account_blocks b WHERE (b.user=? AND b.target=u.id) OR (b.target=? AND b.user=u.id)) ORDER BY ${sort} LIMIT 25 OFFSET ?`).bind(id,pattern,id,id,offset).all(),
db.prepare('SELECT low,high,requester,state,created,updated FROM friendships WHERE low=? OR high=? ORDER BY updated DESC').bind(id,id).all(),
db.prepare(personSelect+'WHERE u.id IN(SELECT CASE WHEN low=? THEN high ELSE low END FROM friendships WHERE low=? OR high=?) ORDER BY lower(u.username)').bind(id,id,id).all(),
db.prepare(personSelect+'WHERE u.id IN(SELECT target FROM account_blocks WHERE user=?) ORDER BY lower(u.username)').bind(id).all()
]);return Response.json({people:people.results.slice(0,24),hasMore:people.results.length>24,relationships:relationships.results,contacts:contacts.results,blocked:blocked.results},{headers});
}catch{return Response.json({error:'Could not load accounts. Please retry.'},{status:503,headers});}}
const input=z.object({action:z.enum(['request','accept','decline','cancel','remove','block','unblock']),target:z.string().uuid()});
export async function POST(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid request origin.'},{status:403});try{const account=await getAccountUser();if(!account)return Response.json({error:'Sign in to manage friends.'},{status:401});const body=await req.text();if(body.length>1024)return Response.json({error:'Request too large.'},{status:413});const parsed=input.safeParse(JSON.parse(body));if(!parsed.success)return Response.json({error:'Choose a valid account and action.'},{status:400});const p=parsed.data,id=account.userId,db=database(),now=Date.now();if(p.target===id)return Response.json({error:'Choose another account.'},{status:400});if(!await db.prepare('SELECT a.id FROM auth_accounts a JOIN users u ON u.id=a.id WHERE a.id=?').bind(p.target).first())return Response.json({error:'Account not found.'},{status:404});const[low,high]=[id,p.target].sort();
if(p.action==='unblock'){await db.prepare('DELETE FROM account_blocks WHERE user=? AND target=?').bind(id,p.target).run();return Response.json({ok:true});}
if(p.action==='block'){await db.prepare('INSERT INTO account_blocks(user,target,created) VALUES(?,?,?) ON CONFLICT(user,target) DO NOTHING').bind(id,p.target,now).run();return Response.json({ok:true});}
if(await db.prepare('SELECT user FROM account_blocks WHERE (user=? AND target=?) OR (user=? AND target=?)').bind(id,p.target,p.target,id).first())return Response.json({error:'This connection is unavailable.'},{status:403});
if(p.action==='request'){const key=await digest('friend-requests:'+id);const limit=await db.prepare('INSERT INTO auth_limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<=? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<=? THEN excluded.expires ELSE expires END RETURNING count').bind(key,now+300000,now,now).first<{count:number}>();if(limit&&limit.count>20)return Response.json({error:'You’ve sent a lot of requests. Try again in five minutes.'},{status:429});const existing=await db.prepare('SELECT requester,state FROM friendships WHERE low=? AND high=?').bind(low,high).first<{requester:string;state:string}>();if(existing)return existing.requester===id||existing.state==='accepted'?Response.json({ok:true}):Response.json({error:'This account has already sent you a request. Accept it instead.'},{status:409});await db.prepare("INSERT INTO friendships(low,high,requester,state,created,updated) VALUES(?,?,?,'pending',?,?) ON CONFLICT(low,high) DO NOTHING").bind(low,high,id,now,now).run();return Response.json({ok:true});}
let result;
if(p.action==='accept')result=await db.prepare("UPDATE friendships SET state='accepted',updated=? WHERE low=? AND high=? AND state='pending' AND requester!=?").bind(now,low,high,id).run();
else if(p.action==='decline')result=await db.prepare("DELETE FROM friendships WHERE low=? AND high=? AND state='pending' AND requester!=?").bind(low,high,id).run();
else if(p.action==='cancel')result=await db.prepare("DELETE FROM friendships WHERE low=? AND high=? AND state='pending' AND requester=?").bind(low,high,id).run();
else result=await db.prepare("DELETE FROM friendships WHERE low=? AND high=? AND state='accepted'").bind(low,high).run();
return result.meta.changes?Response.json({ok:true}):Response.json({error:'This connection changed. Refresh and try again.'},{status:409});
}catch(e){return Response.json({error:String(e).includes('Connection unavailable')?'This connection is unavailable.':'Could not save this change. Please retry.'},{status:400});}}
